project_id = "swrjhypfsbvlxlrpbsve"

[functions.send-message]
verify_jwt = false

[functions.toggle-reaction]
verify_jwt = false

[functions.save-profile]
verify_jwt = false

[functions.submit-feedback]
verify_jwt = false
