import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = f => fs.readFileSync(path.join(root,f),'utf8');
const app=read('src/App.tsx'), css=read('src/styles.css'), catalog=read('src/data/catalog.ts'), validation=read('src/lib/validation.ts'), schema=read('supabase/schema.sql');
const send=read('supabase/functions/send-message/index.ts'), reaction=read('supabase/functions/toggle-reaction/index.ts'), profile=read('supabase/functions/save-profile/index.ts');
const migrations=fs.readdirSync(path.join(root,'supabase/migrations')).map(f=>fs.readFileSync(path.join(root,'supabase/migrations',f),'utf8')).join('\n');
const pkg=JSON.parse(read('package.json'));
const checks=[];
const privateShieldVideoPattern=/private-shield\.(?:webm|mp4)/;
const avatarMatches=[...catalog.matchAll(/\{ id: (\d+), src: '([^']+)' \}/g)];
const avatarIds=avatarMatches.map(m=>Number(m[1])), avatarSrcs=avatarMatches.map(m=>m[2]);
const themeBlock=catalog.slice(catalog.indexOf('export const THEMES = ['),catalog.indexOf('export const EMOJIS'));
const themeIds=[...themeBlock.matchAll(/\['([^']+)','([^']+)'/g)].map(m=>m[1]);
const reactions=['\u{1F44D}','\u{2764}\u{FE0F}','\u{1F602}','\u{1F62E}','\u{1F622}','\u{1F621}','\u{1F389}','\u{1F64F}'];
const releaseAudit=process.env.RELEASE_AUDIT==='1';
const ok=(name,test)=>checks.push([name,!!test]);
ok('exactly 100 avatar records',avatarMatches.length===100);
ok('avatar IDs 1..100 unique',avatarIds.length===100&&new Set(avatarIds).size===100&&avatarIds.every((x,i)=>x===i+1));
ok('100 avatar image assets unique',avatarSrcs.length===100&&new Set(avatarSrcs).size===100&&avatarSrcs.every(x=>fs.existsSync(path.join(root,'public',x.replace(/^\//,'')))));

ok('25 themes',themeIds.length===25&&new Set(themeIds).size===25);
ok('exactly 8 reactions',reactions.length===8);
ok('500-char client validation',/\[\.\.\.value\]\.length > 500/.test(validation));
ok('English-only client validation',/isEnglishOnly/.test(validation));
ok('offensive filter client',/hasOffensiveLanguage/.test(validation));
ok('server-side 500-char validation',/\[\.\.\.body\]\.length>500/.test(send));
ok('server-side English validation',/englishOnly\(body\)/.test(send));
ok('server-side offensive filter',/offensive\(body\)/.test(send));
ok('server-side 3-in-10 rate limit',/interval '10 seconds'/.test(schema)&&/recent_count >= 3/.test(schema));
ok('atomic per-user rate-limit lock',/pg_advisory_xact_lock/.test(schema));
ok('5-minute individual expiry',/interval '5 minutes'/.test(schema)&&/expires_at/.test(schema));
ok('expired rows physically sweepable',/delete from public\.messages where expires_at <= now\(\)/.test(schema));
ok('fixed avatar server validation',/avatar_id integer not null check \(avatar_id between 1 and 100\)/.test(schema)&&/avatarId<=100/.test(send));
ok('fixed theme server validation',/themes\.includes\(p\.themeId\)/.test(profile));
ok('country/subdivision server validation',/iso31661/.test(send)&&/iso31662/.test(send)&&/code\.startsWith\(`\$\{p\.country\}-`\)/.test(send));
ok('exact reaction DB constraint',reactions.every(x=>schema.includes(x))||reactions.every((_,i)=>schema.includes(["U&'\\+1F44D'","U&'\\+2764\\+FE0F'","U&'\\+1F602'","U&'\\+1F62E'","U&'\\+1F622'","U&'\\+1F621'","U&'\\+1F389'","U&'\\+1F64F'"][i])));
ok('reaction server validation',reactions.every(x=>reaction.includes(x))&&/includes\(reaction\)/.test(reaction));
ok('RLS enabled',/enable row level security/.test(schema));
ok('direct message inserts blocked',/messages_no_direct_insert.*for insert.*with check \(false\)/s.test(schema));
ok('private realtime presence policy',/realtime\.topic\(\) = 'global-chat'/.test(schema));
ok('realtime publication',/add table public\.messages/.test(schema)&&/add table public\.message_reactions/.test(schema));
ok('realtime presence count',/presenceState\(\)/.test(app)&&/presence:\{key:selfId\}/.test(app));
ok('realtime cleanup',/removeChannel\(channel\)/.test(app));
ok('anonymous auth',/signInAnonymously/.test(app));
ok('no upload input',!/<input[^>]+type=["']file/i.test(app));
ok('no Notification API',!/new Notification|Notification\.requestPermission/.test(app));
ok('two sounds only',/send\.wav/.test(app)&&/receive\.wav/.test(app)&&!/(notification|alert)\.wav/i.test(app));
ok('four text sizes',/small.*medium.*large.*xl/.test(catalog));
ok('fixed emoji picker',/EMOJIS/.test(app)&&/emoji-pop/.test(app));
ok('private chat UI present',/PrivateChatModal/.test(app)&&/PrivateRoomView/.test(app)&&/create_private_room/.test(app)&&/join_private_room/.test(app));
ok('private clean shield/lock animation',/private-shield-animation/.test(app)&&/private-shield-video/.test(app)&&/private-shield-lock\.mp4/.test(app)&&fs.existsSync(path.join(root,'public/animations/private-shield-lock.mp4'))&&/mix-blend-mode:lighten/.test(css)&&!/ShieldCheck/.test(app));
ok('no placeholder voice-options question mark',!/<span>\?<\/span>/.test(app));
ok('private voice delete uses Storage API',/storage\.from\('private-voice-messages'\)\s*\.remove/.test(app));
ok('private delete-for-everyone DB RPC',/rpc\('delete_private_voice'/.test(app)&&/rpc\('delete_private_message'/.test(app));
ok('private delete-for-me persists locally',/global-chat-private-local-deleted-v1/.test(app)&&/localDeleted\['v:'/.test(app)&&/localDeleted\['m:'/.test(app));
ok('private voice polling fallback is throttled',/setInterval\(\(\)=>void loadVoices\(\),8000\)/.test(app));
ok('private realtime presence count',/presenceState\(\)/.test(app)&&/setPrivateOnline\(Object\.keys\(state\)\.length\)/.test(app));
ok('public sent messages use mine alignment',/current\?['"]mine['"]/.test(app)&&/message-row\.mine/.test(css));
ok('public voice menu has MoreVertical icon',/MoreVertical/.test(app));
ok('public/private typing indicators present',/Someone is typing/.test(app)&&/private-typing/.test(app)&&/event:'typing'/.test(app));
ok('public/private recording indicators present',/Someone is recording/.test(app)&&/private-recording/.test(app)&&/event:'recording'/.test(app));
ok('private send/delete action sounds',/playPrivateAction\('\/sounds\/send\.wav'\)/.test(app));
ok('private voice recording and upload flow',/MediaRecorder/.test(app)&&/private-voice-messages/.test(app)&&/send_private_voice/.test(app)&&/sendRecordedPrivateVoice/.test(app));
ok('private voice local-delete filter survives refresh',/filter\(v=>!localDeleted\['v:'\+v\.id\]\)/.test(app));
ok('mobile search/clear/settings menu',/mobile-header-menu/.test(app)&&/Search/.test(app)&&/Clear Chat/.test(app)&&/Settings/.test(app));

ok('production build script',pkg.scripts?.build==='tsc -b && vite build');
ok('typecheck configs present',fs.existsSync(path.join(root,'tsconfig.app.json'))&&fs.existsSync(path.join(root,'tsconfig.node.json')));
ok('public voice direct-send/cancel flow',/recordedVoiceBlob/.test(app)&&/sendRecordedVoice/.test(app)&&/sendRecordingNow/.test(app)&&/cancelRecording/.test(app)&&/voice-send/.test(app)&&!/voice-finish/.test(app)&&/recorder\.onstop=async/.test(app));
ok('private voice direct-send/cancel flow',/sendRecordedPrivateVoice/.test(app)&&/stopVoice/.test(app)&&/stopVoice\(true\)/.test(app)&&/cancelVoice/.test(app));
ok('public/private voice recorder has live waveform UI',/LiveRecordingWaveform/.test(app)&&/recordingStream/.test(app)&&/getByteTimeDomainData/.test(app)&&/recording-wave/.test(app));
ok('public voice 60-second cap',/elapsed>=60/.test(app)&&/Math\.min\(60000/.test(app));
ok('voice seek control',/type="range"/.test(app)&&/voice-seek/.test(app)&&/currentTime=value/.test(app));
ok('voice playback speeds 1x 1.5x 2x',/1\.5/.test(app)&&/2:1/.test(app)&&/voice-speed-btn/.test(app));
ok('private room 8-character code only',/create_private_room\(p_name text\)/.test(migrations)&&/join_private_room\(p_join_code text\)/.test(migrations)&&/\{8\}/.test(migrations)&&!/privatePassword/.test(app));
ok('private members directory',/get_private_room_members/.test(app)&&/PRIVATE CHAT MEMBERS/.test(app)&&/private-members-btn/.test(app));
ok('private admin moderation RPCs',/remove_private_room_member/.test(migrations)&&/block_private_room_member/.test(migrations)&&/unblock_private_room_member/.test(migrations));
ok('private owner rename',/rename_private_room/.test(app)&&/rename_private_room/.test(migrations)&&/your-private-rename-btn/.test(app));
ok('reply works across text/emoji and voice in public/private',/reply_to_message_id/.test(app)&&/reply_to_voice_id/.test(app)&&/replyToMessageId/.test(app)&&/p_reply_to_id:replyToMessageId/.test(app)&&/p_reply_to_id:replyToMessageId/.test(app));
ok('private reply state is shared with parent sender',/const replyTargetForPrivate=replyTarget;/.test(app)&&!/const \[replyTargetForPrivate,setReplyTargetForPrivate\]=useState/.test(app));
ok('public reply composer shows selected target',/className="reply-composer"/.test(app)&&/Replying to/.test(app));
ok('private voice reply metadata',/reply_to_voice_id/.test(app)&&/private_voice_messages add column if not exists reply_to_voice_id/.test(migrations));
ok('no release .env',!releaseAudit||!fs.existsSync(path.join(root,'.env')));
const reactionLoader=app.slice(app.indexOf('const loadReactions'),app.indexOf('useEffect(()=>{void loadReactions',app.indexOf('const loadReactions')));
ok('private reaction loader avoids per-reaction auth calls',!reactionLoader.includes('supabase.auth.getUser'));
ok('empty-state video uses robust MP4 source',/empty-earth-video[\s\S]*<source src=\"\/earth-animation\.mp4\" type=\"video\/mp4\"\/>/.test(app));


ok('private room waits for auth before presence',/if\(authUserId&&privateRoom\?\.id\)void enterPrivateRoom\(privateRoom\)/.test(app));
ok('private text realtime reconciles optimistic send',/optimistic-private-/.test(app)&&/const optimistic=prev\.find/.test(app)&&/incoming\.created_at/.test(app));
ok('private delete-for-everyone sender gated',/item\.data\.user_id===currentUserId&&<button className="danger"/.test(app));
ok('reply jump supports text and voice targets',/item\.data\.reply_to_voice_id\|\|item\.data\.reply_to_id/.test(app)&&/jumpToPrivateReply/.test(app)&&/voice-\$\{id\}/.test(app));
ok('source mojibake scan clean',!/[ðŸ]|[â]€|Â·|ï¸|�/.test(app)&&!/[ðŸ]|[â]€|Â·|ï¸|�/.test(schema)&&!/[ðŸ]|[â]€|Â·|ï¸|�/.test(migrations));
let failed=0; for(const [name,passed] of checks){console.log(`${passed?'PASS':'FAIL'}  ${name}`);if(!passed)failed++;}
if(failed)process.exit(1); console.log(`\n${checks.length} static checks passed.`);


