import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = f => fs.readFileSync(path.join(root,f),'utf8');
const app=read('src/App.tsx'), catalog=read('src/data/catalog.ts'), validation=read('src/lib/validation.ts'), schema=read('supabase/schema.sql');
const send=read('supabase/functions/send-message/index.ts'), reaction=read('supabase/functions/toggle-reaction/index.ts'), profile=read('supabase/functions/save-profile/index.ts');
const pkg=JSON.parse(read('package.json'));
const checks=[];
const avatarMatches=[...catalog.matchAll(/\{ id: (\d+), emoji: '([^']+)' \}/g)];
const avatarIds=avatarMatches.map(m=>Number(m[1])), avatarEmoji=avatarMatches.map(m=>m[2]);
const themeBlock=catalog.slice(catalog.indexOf('export const THEMES = ['),catalog.indexOf('export const EMOJIS'));
const themeIds=[...themeBlock.matchAll(/\['([^']+)','([^']+)'/g)].map(m=>m[1]);
const reactions=['👍','❤️','😂','😮','😢','😡','🎉','🙏'];
const ok=(name,test)=>checks.push([name,!!test]);
ok('exactly 100 avatar records',avatarMatches.length===100);
ok('avatar IDs 1..100 unique',avatarIds.length===100&&new Set(avatarIds).size===100&&avatarIds.every((x,i)=>x===i+1));
ok('100 avatar visuals genuinely unique',avatarEmoji.length===100&&new Set(avatarEmoji).size===100);
ok('25 themes',themeIds.length===25&&new Set(themeIds).size===25);
ok('exactly 8 reactions',/REACTIONS = \['👍','❤️','😂','😮','😢','😡','🎉','🙏'\]/.test(catalog));
ok('500-char client validation',/\[\.\.\.value\]\.length > 500/.test(validation));
ok('English-only client validation',/isEnglishOnly/.test(validation));
ok('offensive filter client',/hasOffensiveLanguage/.test(validation));
ok('server-side 500-char validation',/\[\.\.\.body\]\.length>500/.test(send));
ok('server-side English validation',/englishOnly\(body\)/.test(send));
ok('server-side offensive filter',/offensive\(body\)/.test(send));
ok('server-side 3-in-10 rate limit',/interval '10 seconds'/.test(schema)&&/recent_count >= 3/.test(schema));
ok('atomic per-user rate-limit lock',/pg_advisory_xact_lock/.test(schema));
ok('5-minute individual expiry',/interval '5 minutes'/.test(schema)&&/expires_at/.test(schema));
ok('expired rows physically sweepable',/delete from public\.messages where expires_at <= now\(\)/.test(schema));
ok('fixed avatar server validation',/avatar_id integer not null check \(avatar_id between 1 and 100\)/.test(schema)&&/avatarId<=100/.test(send));
ok('fixed theme server validation',/themes\.includes\(p\.themeId\)/.test(profile));
ok('country/subdivision server validation',/iso31661/.test(send)&&/iso31662/.test(send)&&/code\.startsWith\(`\$\{p\.country\}-`\)/.test(send));
ok('exact reaction DB constraint',/reaction text not null check \(reaction in \('👍','❤️','😂','😮','😢','😡','🎉','🙏'\)\)/.test(schema));
ok('reaction server validation',reactions.every(x=>reaction.includes(`'${x}'`)));
ok('RLS enabled',/enable row level security/.test(schema));
ok('direct message inserts blocked',/messages_no_direct_insert.*for insert.*with check \(false\)/s.test(schema));
ok('private realtime presence policy',/realtime\.topic\(\) = 'global-chat'/.test(schema));
ok('realtime publication',/add table public\.messages/.test(schema)&&/add table public\.message_reactions/.test(schema));
ok('realtime presence count',/presenceState\(\)/.test(app)&&/presence:\{key:selfId\}/.test(app));
ok('realtime cleanup',/removeChannel\(channel\)/.test(app));
ok('anonymous auth',/signInAnonymously/.test(app));
ok('no upload input',!/<input[^>]+type=["']file/i.test(app));
ok('no Notification API',!/new Notification|Notification\.requestPermission/.test(app));
ok('two sounds only',/send\.wav/.test(app)&&/receive\.wav/.test(app)&&!/(notification|alert)\.wav/i.test(app));
ok('four text sizes',/small.*medium.*large.*xl/.test(catalog));
ok('fixed emoji picker',/EMOJIS/.test(app)&&/emoji-pop/.test(app));
ok('no DM/group/admin UI',!/(direct message|private chat|admin dashboard|user directory|groups?)/i.test(app));
ok('production build script',pkg.scripts?.build==='tsc -b && vite build');
ok('typecheck configs present',fs.existsSync(path.join(root,'tsconfig.app.json'))&&fs.existsSync(path.join(root,'tsconfig.node.json')));
let failed=0; for(const [name,passed] of checks){console.log(`${passed?'PASS':'FAIL'}  ${name}`);if(!passed)failed++;}
if(failed)process.exit(1); console.log(`\n${checks.length} static checks passed.`);
