import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = f => fs.readFileSync(path.join(root,f),'utf8');
const app=read('src/App.tsx'), css=read('src/styles.css'), earth=read('src/EarthGlobe.tsx'), earthMap=read('public/world-countries.svg'), catalog=read('src/data/catalog.ts'), validation=read('src/lib/validation.ts'), schema=read('supabase/schema.sql'), emojiPicker=read('src/EmojiPicker.tsx'), profileIntroPrefs=read('src/lib/profileIntros.ts'), localChatColor=read('src/LocalChatColor.tsx'), eventsUi=read('src/PrivateEventComposer.tsx')+read('src/PrivateEventCard.tsx');
const send=read('supabase/functions/send-message/index.ts'), reaction=read('supabase/functions/toggle-reaction/index.ts'), profile=read('supabase/functions/save-profile/index.ts');
const accountRecovery=read('supabase/functions/account-recovery/index.ts');
const chatControls=read('src/ChatControls.tsx'), privacyReview=read('src/PrivacyReviewCard.tsx'), localCleanup=read('src/LocalDataCleanupControls.tsx'), memberFilters=read('src/MemberFilters.tsx'), roomGlossary=read('src/RoomGlossary.tsx'), publicFeedback=read('src/PublicMessageFeedback.tsx'), personalControlsSql=read('supabase/migrations/20261004100000_personal_controls_and_room_tools.sql'), chatLimitSql=read('supabase/migrations/20261003180000_increase_chat_text_limit_to_550.sql');
const migrations=fs.readdirSync(path.join(root,'supabase/migrations')).map(f=>fs.readFileSync(path.join(root,'supabase/migrations',f),'utf8')).join('\n');
const pkg=JSON.parse(read('package.json'));
const checks=[];
const privateLockVideoPattern=/private-chat-lock-bubbles\.webm/;
const avatarStyles=JSON.parse(read('src/data/avatar-styles.json'));
const avatarCount=avatarStyles.reduce((sum,style)=>sum+style.count,0);
const avatarPickerSlugs=JSON.parse(read('src/data/avatar-picker-style-slugs.json'));
const avatarExtras=JSON.parse(read('src/data/avatar-extra.json'));
const extraCounts=Object.fromEntries(avatarPickerSlugs.filter(slug=>slug!=='initials').map(slug=>[slug,avatarExtras.filter(avatar=>avatar.slug===slug).length]));
const themeBlock=catalog.slice(catalog.indexOf('export const THEMES = ['),catalog.indexOf('export const EMOJIS'));
const themeEntries=[...themeBlock.matchAll(/\['([^']+)','([^']+)','(#[0-9a-f]{6})','(#[0-9a-f]{6})','(#[0-9a-f]{6})','(#[0-9a-f]{6})'/gi)];
const themeIds=themeEntries.map(entry=>entry[1]);
const relativeLuminance=hex=>hex.slice(1).match(/../g).map(channel=>parseInt(channel,16)/255).map(channel=>channel<=.04045?channel/12.92:((channel+.055)/1.055)**2.4).reduce((sum,channel,index)=>sum+channel*[.2126,.7152,.0722][index],0);
const contrastWithWhite=hex=>1.05/(relativeLuminance(hex)+.05);
const themeContrast=(hex,white)=>white?contrastWithWhite(hex):(relativeLuminance(hex)+.05)/.05;
const accessibleThemeGradientContrast=(start,end)=>{
 const raw=Array.from({length:21},(_,sample)=>'#'+[1,3,5].map(index=>Math.round(parseInt(start.slice(index,index+2),16)+(parseInt(end.slice(index,index+2),16)-parseInt(start.slice(index,index+2),16))*sample/20).toString(16).padStart(2,'0')).join(''));
 const whiteMinimum=Math.min(...raw.map(color=>themeContrast(color,true))),blackMinimum=Math.min(...raw.map(color=>themeContrast(color,false))),white=whiteMinimum>=blackMinimum,target=white?0:255;
 const adjusted=raw.map(color=>{const makeCandidate=amount=>'#'+[1,3,5].map(index=>Math.round(parseInt(color.slice(index,index+2),16)+(target-parseInt(color.slice(index,index+2),16))*amount).toString(16).padStart(2,'0')).join('');if(themeContrast(color,white)>=4.6)return color;let low=0,high=1;for(let attempt=0;attempt<20;attempt++){const middle=(low+high)/2;if(themeContrast(makeCandidate(middle),white)>=4.6)high=middle;else low=middle}return makeCandidate(high)});
 let minimum=Infinity;for(let segment=0;segment<20;segment++)for(const sample of [0,.25,.5,.75,1]){const color='#'+[1,3,5].map(index=>Math.round(parseInt(adjusted[segment].slice(index,index+2),16)+(parseInt(adjusted[segment+1].slice(index,index+2),16)-parseInt(adjusted[segment].slice(index,index+2),16))*sample).toString(16).padStart(2,'0')).join('');minimum=Math.min(minimum,themeContrast(color,white))}return minimum;
};
const reactions=['\u{1F44D}','\u{2764}\u{FE0F}','\u{1F602}','\u{1F62E}','\u{1F622}','\u{1F621}','\u{1F389}','\u{1F64F}'];
const releaseAudit=process.env.RELEASE_AUDIT==='1';
const ok=(name,test)=>checks.push([name,!!test]);
ok('61 stable legacy styles and 506 original avatar IDs; A-Z only in Initials',avatarStyles.length===61&&avatarCount===506&&avatarStyles[0].slug==='initials'&&avatarStyles[0].count===26&&avatarStyles.slice(1).every(style=>style.count===8));
const avatarSvgs=Array.from({length:1262},(_,i)=>fs.existsSync(path.join(root,'public','avatars',`avatar-${i+1}.svg`))?fs.readFileSync(path.join(root,'public','avatars',`avatar-${i+1}.svg`),'utf8'):'');
ok('1262 unique SVG assets, including every generated variant',avatarSvgs.every(Boolean)&&new Set(avatarSvgs).size===1262);
const canonicalAvatarSvgs=avatarSvgs.map(svg=>svg.replace(/<metadata\b[^>]*>[\s\S]*?<\/metadata>/g,'').replace(/<!--[\s\S]*?-->/g,'').replace(/-[0-9a-f]{8}(?=["'])/g,'-HASH'));
ok('all avatar artwork stays visually unique after removing DiceBear metadata and generated IDs',canonicalAvatarSvgs.every(Boolean)&&new Set(canonicalAvatarSvgs).size===1262);
ok('1006 picker choices: only 28 selected styles plus A-Z, 35 unique outputs per non-Initials style',avatarPickerSlugs.length===29&&new Set(avatarPickerSlugs).size===29&&avatarPickerSlugs.includes('initials')&&['critters','clay','constellation','gaze','voxel-art'].every(slug=>avatarPickerSlugs.includes(slug))&&avatarPickerSlugs.filter(slug=>slug!=='initials').length===28&&avatarExtras.length===756&&26+(avatarPickerSlugs.length-1)*35===1006&&avatarPickerSlugs.filter(slug=>slug!=='initials').every(slug=>extraCounts[slug]===27)&&avatarPickerSlugs.filter(slug=>slug!=='initials').every(slug=>avatarStyles.find(style=>style.slug===slug)?.count===8)&&avatarPickerSlugs.filter(slug=>slug!=='initials').every(slug=>avatarExtras.filter(avatar=>avatar.slug===slug).every(avatar=>avatar.variant>=8&&avatar.variant<35)));
ok('new avatar IDs are stable and sequential from 507 to 1262',avatarExtras.length===756&&avatarExtras.every((avatar,index)=>avatar.id===507+index&&avatar.src===`/avatars/avatar-${avatar.id}.svg`));
ok('existing IDs through 1154 stay stable; new styles append as IDs 1155-1262',avatarExtras.filter(avatar=>avatar.id<=782).length===276&&avatarExtras.filter(avatar=>avatar.id<=782).every(avatar=>avatar.variant>=8&&avatar.variant<20)&&avatarExtras.filter(avatar=>avatar.id>=783&&avatar.id<=1127).length===345&&avatarExtras.filter(avatar=>avatar.id>=783&&avatar.id<=1127).every(avatar=>avatar.variant>=20&&avatar.variant<35)&&avatarExtras.filter(avatar=>avatar.slug==='critters').length===27&&avatarExtras.filter(avatar=>avatar.slug==='critters').every((avatar,index)=>avatar.id===1128+index&&avatar.variant===8+index)&&['clay','constellation','gaze','voxel-art'].every((slug,styleIndex)=>avatarExtras.filter(avatar=>avatar.slug===slug).length===27&&avatarExtras.filter(avatar=>avatar.slug===slug).every((avatar,index)=>avatar.id===1155+styleIndex*27+index&&avatar.variant===8+index)));

ok('40 unique themes; 15 new themes have distinct accents and WCAG AA button-text contrast',themeEntries.length===40&&new Set(themeIds).size===40&&new Set(themeEntries.map(entry=>entry.slice(3,7).join(':'))).size===40&&new Set(themeEntries.slice(25).flatMap(entry=>[entry[5],entry[6]])).size===30&&themeEntries.slice(25).every(entry=>contrastWithWhite(entry[5])>=4.5&&contrastWithWhite(entry[6])>=4.5));
ok('all 40 theme CTA gradients maintain AA text contrast after foreground correction',themeEntries.length===40&&themeEntries.every(entry=>accessibleThemeGradientContrast(entry[5],entry[6])>=4.5));
ok('theme buttons calculate contrast-safe foregrounds and gradient backgrounds',app.includes('function themeButtonText(stops:string[])')&&app.includes('function accessibleThemeGradient(stops:string[],foreground:string)')&&app.includes("setProperty('--theme-button-text'")&&app.includes("setProperty('--theme-button-gradient'")&&app.includes("setProperty('--theme-primary-gradient'")&&app.includes("setProperty('--theme-primary-text'")&&css.includes('var(--theme-button-text,#fff)')&&css.includes('var(--theme-button-gradient)')&&css.includes('var(--theme-primary-gradient)')&&css.includes('var(--theme-primary-text,#fff)'));
ok('all 40 themes are accepted by server-side profile validation',themeIds.length===40&&themeIds.every(id=>profile.includes(`'${id}'`))&&/themes\.includes\(p\.themeId\)/.test(profile));
ok('exactly 8 reactions',reactions.length===8);
ok('550-char client validation',/\[\.\.\.value\]\.length > 550/.test(validation));
ok('English-only client validation',/isEnglishOnly/.test(validation));
ok('offensive filter client',/hasOffensiveLanguage/.test(validation));
ok('server-side 550-char validation',/\[\.\.\.body\]\.length>550/.test(send)&&migrations.includes('check (char_length(btrim(body)) between 1 and 550)')&&migrations.includes("v_definition := replace(v_definition, '>500', '>550')"));
ok('server-side English validation',/englishOnly\(body\)/.test(send));
ok('server-side offensive filter',/offensive\(body\)/.test(send));
ok('server-side 3-in-10 rate limit',/interval '10 seconds'/.test(schema)&&/recent_count >= 3/.test(schema));
ok('atomic per-user rate-limit lock',/pg_advisory_xact_lock/.test(schema));
ok('5-minute individual expiry',/interval '5 minutes'/.test(schema)&&/expires_at/.test(schema));
ok('expired rows physically sweepable',/delete from public\.messages where expires_at <= now\(\)/.test(schema));
ok('1262 avatar server and database validation',/avatar_id integer not null check \(avatar_id between 1 and 1262\)/.test(schema)&&/avatarId<=1262/.test(send)&&/avatarId > 1262/.test(profile)&&read('supabase/migrations/20261002130000_expand_avatar_choices_to_1262.sql').includes('avatar_id between 1 and 1262'));
ok('public voice RPC accepts the expanded avatar catalog',read('supabase/migrations/20261002170000_fix_voice_avatar_id_limit.sql').includes('p_avatar_id not between 1 and 1262'));
ok('settings save confirms server success, shows errors, and disables repeat clicks',app.includes('The server did not confirm the profile update')&&app.includes('settingsSaveError&&')&&app.includes('savingSettings} onClick={()=>void saveSettings()}'));
ok('Realtime publication includes every table listened to by the global chat',/public\.messages[\s\S]*public\.voice_messages[\s\S]*public\.message_reactions[\s\S]*public\.voice_reactions/.test(schema)&&read('supabase/migrations/20261002110000_enable_public_chat_realtime.sql').includes("tablename='voice_reactions'"));
ok('Realtime recovery refreshes on subscription and polls only while database changes are unhealthy',/\.on\('system',\s*\{\}/.test(app)&&/void refreshNow\(\)/.test(app)&&/if\(!postgresChangesReady\)void refreshNow\(\)/.test(app));
ok('private and friend chats catch up after Realtime reconnect and use fallback only when degraded',/if\(!privateChangesReady\)void loadPrivateMessages/.test(app)&&/if\(!privateVoiceChangesReady\)void loadVoices/.test(app)&&/if\(!postgresChangesReady\)void fetchMessages\(\)/.test(read('src/FriendsPanel.tsx')));
ok('fixed theme server validation',/themes\.includes\(p\.themeId\)/.test(profile));
ok('country/subdivision server validation',/iso31661/.test(send)&&/iso31662/.test(send)&&/code\.startsWith\(`\$\{p\.country\}-`\)/.test(send));
ok('Feedback submit reports backend errors and requires confirmed success',app.includes("edgeFunctionErrorMessage(error,'Could not submit the report")&&app.includes("if(!data?.ok) throw new Error(data?.error"));
ok('Feedback backend validates the user and supports older report-table schemas',read('supabase/functions/submit-feedback/index.ts').includes('admin.auth.getUser(token)')&&read('supabase/functions/submit-feedback/index.ts').includes('compatibleRow')&&read('supabase/functions/submit-feedback/index.ts').includes('return json({ ok: true'));
ok('Feedback schema repair grants backend insert access and restores required columns',read('supabase/migrations/20261002190000_repair_feedback_reports_schema.sql').includes('add column if not exists report_type')&&read('supabase/migrations/20261002190000_repair_feedback_reports_schema.sql').includes('grant all privileges on public.feedback_reports to service_role')&&read('supabase/migrations/20261002190000_repair_feedback_reports_schema.sql').includes("notify pgrst, 'reload schema'"));
ok('Feedback insert failures include a diagnostic database code',read('supabase/functions/submit-feedback/index.ts').includes('Could not save the report (${dbCode})'));
ok('exact reaction DB constraint',reactions.every(x=>schema.includes(x))||reactions.every((_,i)=>schema.includes(["U&'\\+1F44D'","U&'\\+2764\\+FE0F'","U&'\\+1F602'","U&'\\+1F62E'","U&'\\+1F622'","U&'\\+1F621'","U&'\\+1F389'","U&'\\+1F64F'"][i])));
ok('reaction server validation',reactions.every(x=>reaction.includes(x))&&/includes\(reaction\)/.test(reaction));
ok('RLS enabled',/enable row level security/.test(schema));
ok('direct message inserts blocked',/messages_no_direct_insert.*for insert.*with check \(false\)/s.test(schema));
ok('private realtime presence policy',/realtime\.topic\(\) = 'global-chat'/.test(schema));
ok('realtime publication',/add table public\.messages/.test(schema)&&/add table public\.message_reactions/.test(schema)&&/add table public\.voice_messages/.test(schema)&&/add table public\.voice_reactions/.test(schema));
ok('realtime presence count',/presenceState\(\)/.test(app)&&/presence:\{key:selfId\}/.test(app));
ok('realtime cleanup',/removeChannel\(channel\)/.test(app));
ok('anonymous auth',/signInAnonymously/.test(app));
ok('no upload input',!/<input[^>]+type=["']file/i.test(app));
ok('browser notifications require a test action or granted permission',app.includes("if(permission==='default')permission=await Notification.requestPermission()")&&app.includes("if(document.hidden&&typeof Notification!=='undefined'&&Notification.permission==='granted')")&&app.includes('TEST NOTIFICATION &amp; SOUND'));
ok('public sender ignore list is account-local with temporary, turn-off and undo controls',app.includes("const PUBLIC_IGNORE_KEY_PREFIX='global-chat-public-ignore-v1:'")&&app.includes('persistPublicIgnoreList(authUserId,next)')&&app.includes('onIgnore(60*60*1000)')&&app.includes('onIgnore(24*60*60*1000)')&&app.includes('Until I turn it off')&&app.includes('onUnignore={unignorePublicSender}')&&app.includes('onClick={()=>unignorePublicSender(ignoreNotice.userId)}')&&app.includes('!activePublicIgnoreList[message.user_id]'));
ok('two sounds only',/send\.wav/.test(app)&&/receive\.wav/.test(app)&&!/(notification|alert)\.wav/i.test(app));
ok('four text sizes',/small.*medium.*large.*xl/.test(catalog));
ok('scrollable emoji picker with browser-local favorites',/emoji-picker-track/.test(emojiPicker)&&/scrollBy/.test(emojiPicker)&&/favoriteKey\(userId\)/.test(emojiPicker)&&/emoji-favorites-track/.test(css));
ok('private chat UI present',/PrivateChatModal/.test(app)&&/PrivateRoomView/.test(app)&&/create_private_room/.test(app)&&/join_private_room/.test(app));
ok('private clean lock/chat animation',/private-lock-animation/.test(app)&&/private-lock-video/.test(app)&&privateLockVideoPattern.test(app)&&fs.existsSync(path.join(root,'public/animations/private-chat-lock-bubbles.webm'))&&!/private-shield|shield-lock/.test(app+css));
ok('no placeholder voice-options question mark',!/<span>\?<\/span>/.test(app));
ok('private voice delete uses Storage API',/storage\.from\('private-voice-messages'\)\s*\.remove/.test(app));
ok('private delete-for-everyone DB RPC',/rpc\('delete_private_voice'/.test(app)&&/rpc\('delete_private_message'/.test(app));
ok('private delete-for-me persists locally',/global-chat-private-local-deleted-v1/.test(app)&&/localDeleted\['v:'/.test(app)&&/localDeleted\['m:'/.test(app));
ok('private voice polling is only used while Realtime is degraded',/if\(!privateVoiceChangesReady\)void loadVoices\(\)/.test(app)&&/setInterval\(\(\)=>\{if\(!privateVoiceChangesReady\)void loadVoices\(\)\},5000\)/.test(app));
ok('private realtime presence count',/presenceState\(\)/.test(app)&&/setPrivateOnline\(Object\.keys\(state\)\.length\)/.test(app));
ok('public sent messages use mine alignment',/current\?['"]mine['"]/.test(app)&&/message-row\.mine/.test(css));
ok('public voice menu has MoreVertical icon',/MoreVertical/.test(app));
ok('public/private typing indicators present',/Someone is typing/.test(app)&&/private-typing/.test(app)&&/event:'typing'/.test(app));
ok('public/private recording indicators present',/Someone is recording/.test(app)&&/private-recording/.test(app)&&/event:'recording'/.test(app));
ok('private send/delete action sounds',/playPrivateAction\('\/sounds\/send\.wav'\)/.test(app));
ok('private voice recording and upload flow',/MediaRecorder/.test(app)&&/private-voice-messages/.test(app)&&/send_private_voice/.test(app)&&/sendRecordedPrivateVoice/.test(app));
ok('private voice playback streams with signed URLs, falls back to authenticated download, normalizes MIME, and revokes local audio URLs',app.includes("if(bucket==='private-voice-messages')")&&app.includes('createSignedUrl(v.storage_path,lifetime)')&&app.includes('.from(bucket).download(v.storage_path)')&&app.includes('URL.createObjectURL(playableBlob)')&&app.includes('storedMime===fileMime?data:new Blob([data],{type:fileMime})')&&app.includes('URL.revokeObjectURL(objectUrlRef.current)'));
ok('voice playback keeps private storage isolated and preserves signed links for other buckets',app.includes("if(bucket==='private-voice-messages')")&&app.includes("else if(bucket!=='voice-messages')")&&app.includes('createSignedUrl(v.storage_path'));
ok('private voice playback prepares audio before the next tap without changing bubble height',app.includes('startPlayback(existing)')&&app.includes('Audio is ready. Tap play again to start.')&&css.includes('.voice-player-error{position:absolute'));
ok('public voice delete-for-everyone removes the row optimistically and restores it on failure',app.includes('pendingVoiceDeleteIdsRef.current.add(v.id)')&&app.includes('setVoiceMessages(prev=>prev.filter(x=>x.id!==v.id))')&&app.includes('Could not delete this voice message. Please try again.'));
ok('private voice local-delete filter survives refresh',/filter\(v=>!localDeleted\['v:'\+v\.id\]\)/.test(app));
ok('header search/clear/settings menu',/header-more-menu/.test(app)&&/Search/.test(app)&&/Clear Chat/.test(app)&&/Settings/.test(app)&&/MoreVertical/.test(app));

ok('production build script',pkg.scripts?.build==='tsc -b && vite build');
ok('typecheck configs present',fs.existsSync(path.join(root,'tsconfig.app.json'))&&fs.existsSync(path.join(root,'tsconfig.node.json')));
ok('public voice direct-send/cancel flow',/recordedVoiceBlob/.test(app)&&/sendRecordedVoice/.test(app)&&/public-record-main/.test(app)&&/cancelRecording/.test(app)&&!/voice-finish/.test(app)&&/recorder\.onstop=/.test(app));
ok('private voice direct-send/cancel flow',/sendRecordedPrivateVoice/.test(app)&&/stopVoice/.test(app)&&/stopVoice\(true\)/.test(app)&&/cancelVoice/.test(app));
ok('public/private voice recorder has live waveform UI',/LiveRecordingWaveform/.test(app)&&/recordingStream/.test(app)&&/getByteTimeDomainData/.test(app)&&/recording-wave/.test(app)&&/if\(!stream\)\{if\(!staticPreview\)return null;return/.test(app));
ok('voice playback waveform animates only while playing',app.includes("className={playing?'active':'static'}")&&/\.voice-wave-player i\.static\{[^}]*animation:none/.test(css)&&/\.voice-wave-player i\.active\{[^}]*animation:voiceWave/.test(css)&&/@media\(prefers-reduced-motion:reduce\)\{\.voice-wave-player i\.active\{animation:none/.test(css));
ok('public voice ready preview hides waveform and keeps sent playback waveform',app.includes('{recording&&<LiveRecordingWaveform stream={recordingStream}/>}')&&app.includes('<VoicePlayer key={v.id} v={v}/><button className="voice-menu-btn"')&&/className="voice-seek"/.test(app));
ok('public voice waveform animates only while recording',/\.public-voice-composer-v2 \.recording-wave i\{[^}]*animation:none/.test(css)&&/\.public-voice-composer-v2\.is-recording \.recording-wave i\.active\{[^}]*animation:voiceWave/.test(css));
ok('public voice 60-second cap',/elapsed>=60/.test(app)&&/Math\.min\(60000/.test(app));
ok('voice seek control',/type="range"/.test(app)&&/voice-seek/.test(app)&&/currentTime=value/.test(app));
ok('voice playback speeds 1x 1.5x 2x',/1\.5/.test(app)&&/2:1/.test(app)&&/voice-speed-btn/.test(app));
ok('private room 8-character code only',/create_private_room\(p_name text\)/.test(migrations)&&/join_private_room\(p_join_code text\)/.test(migrations)&&/\{8\}/.test(migrations)&&!/privatePassword/.test(app));
ok('private members directory',/get_private_room_members/.test(app)&&/PRIVATE CHAT MEMBERS/.test(app)&&/private-room-menu/.test(app));
ok('public, private, and friend chats pause auto-scroll while reading older messages',/autoScrollPaused/.test(app)&&/privateAutoScrollPaused/.test(app)&&/friendAutoScrollPaused/.test(read('src/FriendsPanel.tsx'))&&/Resume auto-scroll/.test(app+read('src/FriendsPanel.tsx')));
ok('default chat section can be saved and opened on sign-in',/defaultChatTab/.test(app)&&/defaultSectionAppliedRef/.test(app));
ok('friend nicknames are local, editable, removable, and use one # prefix',read('src/FriendsPanel.tsx').includes('global-chat-friend-nicknames-v1')&&read('src/FriendsPanel.tsx').includes("replace(/^#+/,'')")&&/REMOVE/.test(read('src/FriendsPanel.tsx')));
ok('profile intro has an 80-character cap, Hidden default, and database-enforced audience RPC',/profileIntroVisibility/.test(app)&&/slice\(0,80\)/.test(app)&&/profile_intro_visibility/.test(profile)&&/char_length\(profile_intro\) <= 80/.test(migrations)&&/default 'hidden'/.test(migrations)&&/get_visible_profile_intros/.test(migrations));
ok('profile intro privacy RPC returns only everyone or accepted-friend intros without blocks',/get_visible_profile_intros/.test(migrations)&&/profile_intro_visibility='everyone'/.test(migrations)&&/public\.friendships/.test(migrations)&&/public\.friend_blocks/.test(migrations)&&/rpc\('get_visible_profile_intros'/.test(profileIntroPrefs));
ok('voice playback speed is available in public/private and friend chats',/voice-speed-btn/.test(app)&&/friend-voice-speed/.test(read('src/FriendsPanel.tsx'))&&/playbackRate=next/.test(read('src/FriendsPanel.tsx')));
ok('per-chat color labels are browser-local for public, private, and friend chats',/global-chat-local-chat-colors-v1/.test(localChatColor)&&/chatKey="public"/.test(app)&&/chatKey=\{`private:\$\{room\.id\}`\}/.test(app)&&/chatKey=\{`friend:\$\{selected\.user_id\}`\}/.test(read('src/FriendsPanel.tsx')));
ok('emoji favorites are stored locally per account in this browser',/global-chat-emoji-favorites-v1/.test(emojiPicker)&&/toggleFavorite/.test(emojiPicker));
ok('private room events enforce member-only create and Going/Maybe/No RSVP',/create_private_chat_event/.test(migrations)&&/respond_private_chat_event/.test(migrations)&&/Going/.test(eventsUi)&&/Maybe/.test(eventsUi)&&/No/.test(eventsUi)&&/private_chat_event_rsvps_read_members/.test(migrations));
ok('new profile settings and chat event cards have mobile responsive styles',/profile-intro-visible/.test(css)&&/private-event-card/.test(css)&&/@media\(max-width:600px\)/.test(css));
ok('private admin moderation RPCs',/remove_private_room_member/.test(migrations)&&/block_private_room_member/.test(migrations)&&/unblock_private_room_member/.test(migrations));
ok('private owner rename',/rename_private_room/.test(app)&&/rename_private_room/.test(migrations)&&/your-private-rename-btn/.test(app));
ok('reply works across text/emoji and voice in public/private',/reply_to_message_id/.test(app)&&/reply_to_voice_id/.test(app)&&/replyToMessageId/.test(app)&&/p_reply_to_id:replyToMessageId/.test(app)&&/p_reply_to_id:replyToMessageId/.test(app));
ok('private reply state is shared with parent sender',/const replyTargetForPrivate=replyTarget;/.test(app)&&!/const \[replyTargetForPrivate,setReplyTargetForPrivate\]=useState/.test(app));
ok('public reply composer shows selected target',/className="reply-composer"/.test(app)&&/Replying to/.test(app));
ok('private voice reply metadata',/reply_to_voice_id/.test(app)&&/private_voice_messages add column if not exists reply_to_voice_id/.test(migrations));
ok('private voice message has inline Reply action',/Reply to voice message/.test(app)&&/setReplyTargetForPrivate\(\{\.\.\.item\.data,id:`voice-reply-/.test(app));
ok('public and private voice uploads render optimistically',/optimistic-public-voice-/.test(app)&&/optimistic-private-voice-/.test(app)&&/URL\.createObjectURL\(blob\)/.test(app));
ok('no release .env',!releaseAudit||!fs.existsSync(path.join(root,'.env')));
const reactionLoader=app.slice(app.indexOf('const loadReactions'),app.indexOf('useEffect(()=>{void loadReactions',app.indexOf('const loadReactions')));
ok('private reaction loader avoids per-reaction auth calls',!reactionLoader.includes('supabase.auth.getUser'));
ok('public empty state uses a rotating globe with real country boundaries and respects reduced-motion settings',app.includes("import EarthGlobe from './EarthGlobe'")&&app.includes('<EarthGlobe/>')&&earth.includes('earth-map-layer')&&(earth.match(/href="\/world-countries\.svg"/g)||[]).length===3&&(earthMap.match(/<path d=/g)||[]).length>=200&&earthMap.includes('Natural Earth 1:50m Admin 0')&&css.includes('@keyframes earth-map-turn')&&css.includes('prefers-reduced-motion:reduce){.earth-map-layer{animation:none')&&!app.includes('earth-animation.mp4'));


ok('private room waits for auth before presence',/if\(authUserId&&privateRoom\?\.id\)void enterPrivateRoom\(privateRoom\)/.test(app));
ok('private text realtime reconciles optimistic send',/optimistic-private-/.test(app)&&/const optimistic=prev\.find/.test(app)&&/incoming\.created_at/.test(app));
ok('private delete-for-everyone sender gated',/item\.data\.user_id===currentUserId&&<button className="danger"/.test(app));
ok('reply jump supports text and voice targets',/item\.data\.reply_to_voice_id\|\|item\.data\.reply_to_id/.test(app)&&/jumpToPrivateReply/.test(app)&&/voice-\$\{id\}/.test(app));
ok('source mojibake scan clean',!/[ðŸ]|[â]€|Â·|ï¸|�/.test(app)&&!/[ðŸ]|[â]€|Â·|ï¸|�/.test(schema)&&!/[ðŸ]|[â]€|Â·|ï¸|�/.test(migrations));
const friends=fs.readFileSync(path.join(root,'src/FriendsPanel.tsx'),'utf8');
const friendsSql=fs.readFileSync(path.join(root,'supabase/migrations/20260926140000_friends_foundation.sql'),'utf8');
ok('Friends header button and panel integrated',/friends-top-btn/.test(app)&&/FriendsPanel/.test(app));
ok('Friends requests, accepted list and discovery UI',/Requests/.test(friends)&&/Find people/.test(friends)&&/friendships/.test(friends));
ok('Friends request and acceptance use secured RPCs',/send_friend_request/.test(friends)&&/respond_friend_request/.test(friends)&&/security definer/i.test(friendsSql));
ok('Friends request cooldown enforced server-side',/interval '5 minutes'/.test(friendsSql));
ok('Friend direct text messaging UI and database',/friend_messages/.test(friends)&&/friend_messages/.test(friendsSql));
ok('Friend text messages and edits use the shared 550-character limit',chatLimitSql.includes("'public.friend_messages'")&&chatLimitSql.includes("'edit_friend_message'")&&chatLimitSql.includes('between 1 and 550'));
ok('Friend messages require accepted friendship and no blocks',/friendships/.test(friendsSql)&&/friend_blocks/.test(friendsSql)&&/friend_messages_read_friends/.test(friendsSql));
ok('Friend requests can be rejected and cancelled',/respond\(r\.id,false\)/.test(friends)&&/cancel_friend_request/.test(friends)&&/status='cancelled'/.test(friendsSql+fs.readFileSync(path.join(root,'supabase/migrations/20260926150000_friend_request_lifecycle_cooldown.sql'),'utf8')));
ok('Friend request cooldown serialized against concurrent sends',/pg_advisory_xact_lock/.test(fs.readFileSync(path.join(root,'supabase/migrations/20260926150000_friend_request_lifecycle_cooldown.sql'),'utf8')));
ok('Public message menu includes Add Friend without duplicate Reply',/Add Friend/.test(app)&&!/onClick=\{\(\)=>\{onReply\(\);setMenu\(false\)\}\}>\s*<ReplyIcon/.test(app));

const friendsSource=read('src/FriendsPanel.tsx');
const realtimeActivity=read('src/lib/realtimeActivity.ts');
const friendFixSql=read('supabase/migrations/20260927150000_fix_friend_chat_rls_and_unblock.sql');
ok('friend text send uses optimistic local bubble',/const optimistic:ChatItem/.test(friendsSource)&&/setMessages\(v=>\[\.\.\.v,optimistic\]\)/.test(friendsSource));
ok('friend message UI has responsive public-chat-style rows',friendsSource.includes('friend-message-row')&&read('src/styles.css').includes('.friend-message-row'));
ok('friend hidden-message upsert has update grant',/GRANT SELECT, INSERT, UPDATE, DELETE ON public\.friend_message_hidden TO authenticated/.test(friendFixSql));
ok('friend unblock restores accepted relationship',/INSERT INTO public\.friendships/.test(friendFixSql)&&/CREATE OR REPLACE FUNCTION public\.unblock_friend/.test(friendFixSql));
const friendCalls=read('src/FriendsCallCenter.tsx');
const privateCalls=read('src/PrivateCallCenter.tsx');
const callAudio=read('src/callAudio.ts');
const uidMigration=read('supabase/migrations/20260929120000_randomize_public_uids.sql');
const uidBaseMigration=read('supabase/migrations/20260928120000_friends_calls_and_public_uid.sql');
ok('Friends voice call uses WebRTC and incoming-call controls',friendCalls.includes('RTCPeerConnection')&&friendCalls.includes('INCOMING VOICE CALL')&&friendCalls.includes('ACCEPT')&&friendCalls.includes('DECLINE'));
ok('Friends voice calls validate accepted friendship and blocks',friendCalls.includes('check_friend_call_target')&&uidBaseMigration.includes('check_friend_call_target'));
ok('Friends call manager remains mounted while browsing Friends',friendsSource.includes('<FriendsCallCenter')&&friendsSource.indexOf('<FriendsCallCenter')<friendsSource.indexOf('{selected?<'));
ok('Private and Friends calls use one shared active-call lease',callAudio.includes('activeCallOwner')&&callAudio.includes('claimVoiceCall')&&privateCalls.includes('claimVoiceCall(callOwnerRef.current)')&&friendCalls.includes('claimVoiceCall(callOwner.current)')&&privateCalls.includes('End the other voice call')&&friendCalls.includes('End the other voice call'));
ok('Both call flows deduplicate pending microphone requests and release the mic on cleanup',privateCalls.includes('localStreamRequestRef.current)return localStreamRequestRef.current')&&friendCalls.includes('if(micRequest.current)return micRequest.current')&&privateCalls.includes('localStreamRef.current?.getTracks().forEach(t=>t.stop())')&&friendCalls.includes('stream.current?.getTracks().forEach(t=>t.stop())'));
ok('Call capture requests echo cancellation, noise suppression, mono audio and disables automatic gain control',callAudio.includes('echoCancellation: true')&&callAudio.includes('noiseSuppression: true')&&callAudio.includes('autoGainControl: false')&&callAudio.includes('channelCount: 1')&&callAudio.includes('liveAudioTracks.length !== 1'));
ok('Both call flows check applied AEC, noise suppression and AGC settings, show warnings, and prevent duplicate audio senders',privateCalls.includes('micSettings?.echoCancellation===false')&&friendCalls.includes('settings?.echoCancellation===false')&&friendCalls.includes('settings?.autoGainControl===true')&&privateCalls.includes('micSettings?.autoGainControl===true')&&privateCalls.includes("position:'fixed',right:18,bottom:150")&&privateCalls.includes('pc.getSenders().some(sender=>sender.track?.id===audioTrack.id)')&&friendCalls.includes('pc.getSenders().some(sender=>sender.track?.id===track.id)'));
ok('Remote call audio stays separate from mic capture and plays below full speaker volume',privateCalls.includes('el.volume=0.8')&&friendCalls.includes('el.volume=0.8')&&!privateCalls.includes('addTrack(e.track')&&!friendCalls.includes('addTrack(e.track'));
ok('Private chat stays mounted behind Friends overlay while one-call lock prevents simultaneous call playback',app.includes('privateRoom&&authUserId?<PrivateRoomView')&&app.includes('friendsOpen&&authUserId&&<Suspense')&&callAudio.includes('activeCallOwner'));
ok('Numeric public UID is random, unique and assigned by database',uidMigration.includes('generate_public_uid')&&uidMigration.includes('gen_random_bytes')&&uidBaseMigration.includes('profiles_public_uid_unique'));
ok('Settings displays numeric public UID beside copy control',app.includes('YOUR UNIQUE USER ID')&&/UID : \{publicUid\|\|/.test(app)&&app.includes('aria-label="Copy UID"'));
ok('New profiles require a user-selected 5-digit password and confirmation',/const valid=[^;]*\^\\d\{5\}\$/.test(app)&&app.includes('Confirm 5-digit password')&&app.includes("action:'set-password',pin:password"));
ok('UID login accepts the chosen password and Settings syncs it to the account',app.includes('Log in with your UID and 5-digit password')&&app.includes('sessionStorage.setItem(ACCOUNT_PASSWORD_KEY,pin)')&&app.includes("action:'remember-password'")&&app.includes('onAccountPasswordChange={onAccountPasswordChange}'));
ok('Login page defines its own theme colors so the Log In button remains visible',css.includes('.account-access-page{--primary:#7c3aed;--accent:#22d3ee;--bg:#080b16;--surface:#10172b;')&&css.includes('.account-access-card .account-login-btn{')&&css.includes('background:linear-gradient(135deg,var(--primary),var(--accent))'));
ok('Settings shows the account password with hide/show, copy, and an explicit change flow',app.includes('Your Password')&&app.includes('aria-label="Copy password"')&&app.includes("showPassword?'Hide password':'Show password'")&&app.includes('CHANGE YOUR PASSWORD')&&app.includes("action:'change-password-with-credentials'"));
ok('Account password is HMAC-verified and stored reversibly only as AES-GCM ciphertext',accountRecovery.includes("hmac(`recovery-code:${pin}`)")&&accountRecovery.includes("name: 'AES-GCM'")&&accountRecovery.includes('password_ciphertext')&&accountRecovery.includes('ACCOUNT_PASSWORD_ENCRYPTION_KEY')&&read('supabase/migrations/20261002200000_persist_account_password.sql').includes('password_ciphertext text'));
ok('Account PIN changes verify the existing PIN and stays active until changed',accountRecovery.includes("action === 'change-password'")&&accountRecovery.includes("payload?.currentPin")&&app.includes('Your password stays active until you change it.'));
ok('Friends directory shows name and location',friendsSource.includes('locationOf(p)')&&uidBaseMigration.includes('get_friend_directory'));
ok('Public, Private, and Friends typing/recording indicators heartbeat and expire cleanly',app.includes('publicTypingHeartbeatRef.current=window.setInterval')&&app.includes('privateTypingHeartbeatRef.current=window.setInterval')&&friendsSource.includes('typingHeartbeat.current=window.setInterval')&&app.includes('publicRecordingHeartbeatRef.current=window.setInterval')&&app.includes('privateRecordingHeartbeatRef.current=window.setInterval')&&friendsSource.includes('recordingHeartbeat.current=window.setInterval')&&friendsSource.includes("event:'recording'")&&friendsSource.includes('friendRecording&&')&&realtimeActivity.includes('window.setTimeout')&&realtimeActivity.includes('window.clearTimeout'));
ok('Friends source mojibake scan clean',!/[ðŸ]|[â]€|Â·|ï¸|�/.test(friendsSource)&&!/[ðŸ]|[â]€|Â·|ï¸|�/.test(friendCalls));

const loginLockSql=read('supabase/migrations/20261002150000_change_recovery_lock_to_five_minutes.sql');
const expirySql=read('supabase/migrations/20261002160000_private_and_friend_messages_expire_after_24h.sql');
const privateVoiceStorageFix=read('supabase/migrations/20261002180000_fix_private_voice_storage_access.sql');
const cleanupFunction=read('supabase/functions/cleanup-voice-messages/index.ts');
ok('UID login permits six checks then enforces a five-minute cooldown',loginLockSql.includes('attempt_count between 0 and 6')&&loginLockSql.includes("interval '5 minutes'")&&loginLockSql.includes('v_attempt_count = 6')&&accountRecovery.includes('Please wait 5 minutes'));
ok('Private and friend text/voice messages expire after 24 hours', ['private_messages','private_voice_messages','friend_messages','friend_voice_messages'].every(table=>expirySql.includes(`public.${table}`))&&expirySql.includes("interval '24 hours'")&&app.includes('24*60*60*1000')&&friendsSource.includes('24*60*60*1000'));
ok('Private voice Storage reads check membership and expiry through a safe helper',privateVoiceStorageFix.includes('security definer')&&privateVoiceStorageFix.includes('v.expires_at > now()')&&privateVoiceStorageFix.includes('public.is_private_room_member(v.room_id)')&&privateVoiceStorageFix.includes('public.can_read_private_voice_storage(name)'));
ok('Expiry cleanup removes expired text rows and voice files for all chat types', ['messages','voice_messages','private_messages','private_voice_messages','friend_messages','friend_voice_messages'].every(table=>cleanupFunction.includes(`'${table}'`))&&cleanupFunction.includes("removeExpiredVoice('private-voice-messages'")&&cleanupFunction.includes("removeExpiredVoice('friend-voice-messages'"));
ok('Private chat list supports pinning and cache-first loading',app.includes('onTogglePin')&&app.includes('PRIVATE_CHAT_PINNED_KEY')&&app.includes('privateChatsLoadedRef'));
ok('Private room code is labelled as private code',app.includes('Private Code')&&app.includes('Private code:'));
ok('Private chats modal stacks above the fixed top bar',read('src/styles.css').includes('.your-private-chats-backdrop{z-index:2000}'));
ok('Temporary room pause is owner-only in UI and enforced for text and voice inserts',app.includes("rpc('set_private_room_message_pause'")&&app.includes('room.owner_id===currentUserId')&&personalControlsSql.includes('before insert on public.private_messages')&&personalControlsSql.includes('before insert on public.private_voice_messages'));
ok('Composer Enter, sound, and formatting preferences are per chat in all chat types',chatControls.includes('enterToSend')&&chatControls.includes('formatting')&&chatControls.includes('chatKey')&&app.includes('publicComposerPreferences.enterToSend')&&app.includes('composerPreferences.enterToSend')&&friendsSource.includes('composerPreferences.enterToSend')&&friendsSource.includes('composerPreferences.formatting'));
ok('Connection quality shows refresh timing and last successful update',app.includes('setConnectionQualityMs(Date.now()-startedAt)')&&app.includes('Last successful update')&&app.includes('measured during message refresh'));
ok('Public message feedback uses valid tags, secured RPC, and batched refresh requests',publicFeedback.includes("['needs_answer', 'Needs answer']")&&personalControlsSql.includes('toggle_public_message_feedback')&&publicFeedback.includes(".in('message_id', ids)")&&publicFeedback.includes('15_000'));
ok('Privacy review exposes profile visibility, notification previews, nicknames, and sign-in history',privacyReview.includes('Profile visibility')&&privacyReview.includes('Notification previews')&&privacyReview.includes('Local friend nicknames')&&privacyReview.includes('Recent sign-ins'));
ok('New-device alert records the account device and displays an in-app notice',app.includes("rpc('record_account_device_login'")&&app.includes('newDeviceNotice')&&personalControlsSql.includes('new_device'));
ok('Friend request note is optional, capped at 200, and stored by the secured RPC',app.includes('p_note:friendRequestNote.trim().slice(0,200)')&&personalControlsSql.includes('char_length(note)<=200')&&personalControlsSql.includes('send_friend_request(p_recipient_id uuid,p_note text)'));
ok('Room glossary is member-readable, supports owner moderation, and has responsive UI',roomGlossary.includes('save_private_room_glossary_term')&&roomGlossary.includes('entry.user_id===userId||canManage')&&app.includes('canManage={room.owner_id===currentUserId}')&&personalControlsSql.includes('is_private_room_member(room_id)'));
ok('Member filters stay local, temporary, and affect only the current viewer',memberFilters.includes('global-chat-member-filters-v1')&&memberFilters.includes('60*60*1000')&&app.includes('!memberFilterState.filters[m.user_id]')&&friendsSource.includes('!friendMemberFilterState.filters[m.sender_id]'));
ok('Local cleanup provides selectable data removal and search-history retention',app.includes('localDataRetentionDays')&&localCleanup.includes('cleanupRoomCache')&&localCleanup.includes('cleanupScroll')&&localCleanup.includes('HISTORY_PREFIX'));
ok('Friend categories and groups are browser-local and filterable',friendsSource.includes('global-chat-friend-organization-v1')&&friendsSource.includes('friendCategoryFilter')&&friendsSource.includes('global-chat-friend-groups-v1')&&friendsSource.includes('friendGroupFilter'));
ok('Snooze reminder displays the active expiry in public, private, and friend chats',app.includes('<SnoozeReminder until={publicSnoozeUntil}/>')&&app.includes('<SnoozeReminder until={snoozeUntil}/>')&&friendsSource.includes('<SnoozeReminder until={snoozeUntil}/>'));
ok('Search history supports reuse, selected deletion, and clear all',chatControls.includes('rememberChatSearch')&&chatControls.includes('Clear selected')&&chatControls.includes('Clear all')&&app.includes('<SearchHistoryButton')&&friendsSource.includes('<SearchHistoryButton'));
ok('Sign-in history is account-scoped with RLS and capped at 12 devices',personalControlsSql.includes('account_device_history_read_self')&&personalControlsSql.includes('using(user_id=auth.uid())')&&personalControlsSql.includes('limit 12')&&privacyReview.includes("from('account_device_history')"));
ok('Color-blind status labels remain optional and default off',app.includes('colorBlindFriendlyIndicators:false')&&app.includes("s.colorBlindFriendlyIndicators===true?'Status: ':''")&&app.includes('Color-blind friendly indicators'));
ok('Composer send failures restore the message and reply target',app.includes('setReplyTarget((previous:any)=>previous||sentReply)')&&app.includes('setReplyTargetForPrivate((previous:any)=>previous||replyTo)')&&friendsSource.includes('setReplyTo(v=>v||replyAtSend)'));
ok('Chat controls and new dialogs include narrow-screen layout rules',css.includes('.feature-modal')&&css.includes('@media(max-width:560px)')&&css.includes('@media(max-width:600px)')&&css.includes('friend-organization-controls'));
ok('Reduced-motion rules and private lock animation asset are present',css.includes('prefers-reduced-motion')&&privateLockVideoPattern.test(app)&&fs.existsSync(path.join(root,'public/animations/private-chat-lock-bubbles.webm')));

let failed=0; for(const [name,passed] of checks){console.log(`${passed?'PASS':'FAIL'}  ${name}`);if(!passed)failed++;}
if(failed)process.exit(1); console.log(`\n${checks.length} static checks passed.`);
