import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { iso31661, iso31662 } from 'iso-3166';
import { Check, ChevronDown, MicOff, Send, Settings, Smile, Volume2, X } from 'lucide-react';
import { supabase } from './lib/supabase';
import { AVATARS, REACTIONS, THEMES, TEXT_SIZES, type TextSize } from './data/catalog';

const EMOJIS = ['😀','😃','😄','😁','😆','😅','😂','🤣','😊','😇','🙂','🙃','😉','😌','😍','🥰','😘','😗','😙','😚','😋','😛','😝','😜','🤪','🤨','🧐','🤓','😎','🤩','🥳','😏','😒','😞','😔','😟','😕','🙁','☹️','😣','😖','😫','😩','🥺','😢','😭','😤','😠','😡','🤬','🤯','😳','🥵','🥶','😱','😨','😰','😥','😓','🤗','👍','👎','👏','🙌','🙏','👋','💪','🔥','❤️','💯'];
import { validateMessage } from './lib/validation';
import './styles.css';

type Profile = { name:string; country:string; subdivision:string; avatarId:number; themeId:string; agreed:boolean };
type TimeFormat = '12h' | '24h';
type ChatMessage = { id:string; user_id:string; name:string; country:string; subdivision:string; avatar_id:number; body:string; created_at:string; expires_at:string };
const PROFILE_KEY='global-chat-profile-v1';
const SETTINGS_KEY='global-chat-settings-v1';

function flag(code:string){return code.toUpperCase().replace(/./g,c=>String.fromCodePoint(c.charCodeAt(0)+127397));}
function readJSON<T>(key:string, fallback:T):T { try { const x=localStorage.getItem(key); return x ? JSON.parse(x) as T : fallback; } catch { return fallback; } }

export default function App(){
  const [profile,setProfile]=useState<Profile|null>(()=>readJSON<Profile|null>(PROFILE_KEY,null));
  const [settings,setSettings]=useState(()=>readJSON(SETTINGS_KEY,{textSize:'medium' as TextSize,sound:true,timeFormat:'12h' as TimeFormat}));
  const [authReady,setAuthReady]=useState(false); const [bootError,setBootError]=useState('');
  useEffect(()=>{ (async()=>{ try { const {data,error}=await supabase.auth.getSession(); if(error) throw error; if(!data.session){ const {error:signInError}=await supabase.auth.signInAnonymously(); if(signInError) throw signInError; } setAuthReady(true); } catch { setBootError('Unable to connect securely. Please refresh and try again.'); } })(); },[]);
  const saveProfile=(p:Profile)=>{localStorage.setItem(PROFILE_KEY,JSON.stringify(p));setProfile(p)};
  if(!authReady) return <div className="boot"><div className="logo-orbit"><Earth3D small /></div><h1>GLOBAL CHAT</h1><p>{bootError||'Connecting securely…'}</p>{bootError&&<button className="primary-btn boot-retry" onClick={()=>location.reload()}>TRY AGAIN</button>}</div>;
  return profile ? <Chat profile={profile} settings={settings} onSettings={setSettings} onProfile={saveProfile}/> : <ProfileSetup onEnter={saveProfile}/>;
}

function ProfileSetup({onEnter}:{onEnter:(p:Profile)=>void}){
  const [name,setName]=useState(''); const [country,setCountry]=useState(''); const [subdivision,setSubdivision]=useState(''); const [avatarId,setAvatarId]=useState(1); const [themeId,setThemeId]=useState('midnight'); const [agreed,setAgreed]=useState(false); const [countryQuery,setCountryQuery]=useState(''); const [subQuery,setSubQuery]=useState('');
  useEffect(()=>{const t=THEMES.find(x=>x.id===themeId)||THEMES[0]; document.documentElement.style.setProperty('--bg',t.bg);document.documentElement.style.setProperty('--surface',t.surface);document.documentElement.style.setProperty('--primary',t.primary);document.documentElement.style.setProperty('--accent',t.accent);},[themeId]);
  const countries=useMemo(()=>iso31661.filter(c=>c.state==='assigned').sort((a,b)=>a.name.localeCompare(b.name)),[]);
  const subdivisions=useMemo(()=>iso31662.filter(s=>s.code.startsWith(country+'-')).sort((a,b)=>a.name.localeCompare(b.name)),[country]);
  const filteredCountries=useMemo(()=>countries.filter(c=>(c.name+' '+c.alpha2+' '+c.alpha3).toLowerCase().includes(countryQuery.toLowerCase())).slice(0,60),[countries,countryQuery]);
  const filteredSubs=useMemo(()=>subdivisions.filter(s=>(s.name+' '+s.code).toLowerCase().includes(subQuery.toLowerCase())).slice(0,120),[subdivisions,subQuery]);
  const selectedCountry=countries.find(c=>c.alpha2===country); const selectedSub=subdivisions.find(s=>s.code===subdivision);
  const valid=name.trim().length>=2 && name.trim().length<=32 && !!selectedCountry && !!selectedSub && agreed;
  const enter=async()=>{if(!valid)return; const p={name:name.trim().replace(/\s+/g,' '),country,subdivision,avatarId,themeId,agreed}; try { const {error}=await supabase.functions.invoke('save-profile',{body:p}); if(error) throw error; onEnter(p); } catch { alert('We could not save your profile. Please check your connection and try again.'); }};
  return <div className="setup-page"><div className="setup-shell">
    <div className="brand"><div className="brand-mark"><Earth3D small /></div><div><h1>GLOBAL CHAT</h1><p>Create Your Profile</p></div></div>
    <div className="setup-grid">
      <section className="card profile-card">
        <label>Name / Nickname</label><input maxLength={32} value={name} onChange={e=>setName(e.target.value)} placeholder="Enter a nickname…" autoComplete="nickname"/>
        <label>Country</label><div className="select-wrap"><input value={countryQuery || (selectedCountry ? `${flag(selectedCountry.alpha2)} ${selectedCountry.name} · ${selectedCountry.alpha2}`:'')} onChange={e=>{setCountryQuery(e.target.value);setCountry('');setSubdivision('')}} placeholder="Search countries…"/><ChevronDown size={18}/></div>
        {countryQuery && !selectedCountry && <div className="option-list">{filteredCountries.map(c=><button key={c.alpha2} onClick={()=>{setCountry(c.alpha2);setCountryQuery('');setSubdivision('')}}>{flag(c.alpha2)} {c.name}<span>{c.alpha2}</span></button>)}</div>}
        {selectedCountry && <div className="selected-chip">{flag(selectedCountry.alpha2)} {selectedCountry.name}<b>{selectedCountry.alpha2}</b><button onClick={()=>{setCountry('');setSubdivision('')}}><X size={14}/></button></div>}
        <label>State / Province / Region</label><div className="select-wrap"><input disabled={!selectedCountry} value={subQuery || (selectedSub ? `${selectedSub.name} · ${selectedSub.code}`:'')} onChange={e=>{setSubQuery(e.target.value);setSubdivision('')}} placeholder={selectedCountry?'Search subdivisions…':'Select a country first'}/><ChevronDown size={18}/></div>
        {selectedCountry && subQuery && !selectedSub && <div className="option-list">{filteredSubs.map(s=><button key={s.code} onClick={()=>{setSubdivision(s.code);setSubQuery('')}}>{s.name}<span>{s.code}</span></button>)}</div>}
        {selectedSub && <div className="selected-chip">{selectedSub.name}<b>{selectedSub.code}</b><button onClick={()=>setSubdivision('')}><X size={14}/></button></div>}
        <label>Choose Your Avatar</label><div className="avatar-grid">{AVATARS.map(a=><button className={`avatar ${avatarId===a.id?'selected':''}`} key={a.id} onClick={()=>setAvatarId(a.id)} aria-label={`Avatar ${a.id}`}>{a.emoji}</button>)}</div>
      </section>
      <section className="card theme-card"><label>Choose Your Theme</label><div className="theme-grid">{THEMES.map(t=><button key={t.id} className={`theme-tile ${themeId===t.id?'selected':''}`} style={{background:t.bg,borderColor:t.primary}} onClick={()=>setThemeId(t.id)}><span style={{background:t.primary}}></span><strong>{t.name}</strong><small>Instant preview</small></button>)}</div>
        <div className="rules"><h3>📜 GLOBAL CHAT RULES</h3><ul><li>English only.</li><li>No bad words or offensive content.</li><li>Max 500 characters per message.</li><li>Max 3 messages every 10 seconds.</li><li>Be respectful. No spam.</li><li>Messages disappear after 5 minutes.</li><li>No photo or file uploads.</li><li>Enjoy the chat responsibly! 🌍</li></ul><label className="agree"><input type="checkbox" checked={agreed} onChange={e=>setAgreed(e.target.checked)}/><span>I agree to the rules</span></label></div>
        <button className="primary-btn" disabled={!valid} onClick={enter}>ENTER CHAT <span>→</span></button>
      </section>
    </div>
  </div></div>
}

function Chat({profile,settings,onSettings,onProfile}:{profile:Profile;settings:{textSize:TextSize;sound:boolean;timeFormat?:TimeFormat};onSettings:(x:any)=>void;onProfile:(x:Profile)=>void}){
  const [messages,setMessages]=useState<ChatMessage[]>([]); const messagesRef=useRef<ChatMessage[]>([]); const messageIdsRef=useRef<string[]>([]); const [online,setOnline]=useState(0); const [reactionCounts,setReactionCounts]=useState<Record<string,Record<string,number>>>({}); const [myReactions,setMyReactions]=useState<Record<string,string[]>>({}); const [authUserId,setAuthUserId]=useState(''); const [text,setText]=useState(''); const [error,setError]=useState(''); const [settingsOpen,setSettingsOpen]=useState(false); const [emojiOpen,setEmojiOpen]=useState(false); const [connected,setConnected]=useState(false); const [sending,setSending]=useState(false); const listRef=useRef<HTMLDivElement>(null); const audioRef=useRef<{send:HTMLAudioElement;receive:HTMLAudioElement}|null>(null); const sessionRef=useRef<any>(null); const pendingRef=useRef<Record<string,{tempId:string;body:string;createdAt:string}>>({}); const sendLockRef=useRef(false);
  const theme=THEMES.find(t=>t.id===profile.themeId) ?? THEMES[0];
  useEffect(()=>{document.documentElement.style.setProperty('--bg',theme.bg);document.documentElement.style.setProperty('--surface',theme.surface);document.documentElement.style.setProperty('--primary',theme.primary);document.documentElement.style.setProperty('--accent',theme.accent);document.documentElement.style.setProperty('--font-size',`${TEXT_SIZES[settings.textSize]}px`);},[theme,settings.textSize]);
  useEffect(()=>{audioRef.current={send:new Audio('/sounds/send.wav'),receive:new Audio('/sounds/receive.wav')};},[]);
  const play=(which:'send'|'receive')=>{if(!settings.sound||!audioRef.current)return;const a=audioRef.current[which];a.currentTime=0;a.play().catch(()=>{});};
  const refresh=useCallback(async()=>{const {data,error}=await supabase.from('messages').select('*').gt('expires_at',new Date().toISOString()).order('created_at',{ascending:true}).limit(100);if(!error&&data){const server=data as ChatMessage[];setMessages(prev=>{const pending=prev.filter(m=>m.id.startsWith('optimistic-')&&pendingRef.current[m.id]);const merged=[...server,...pending.filter(p=>!server.some(m=>m.user_id===p.user_id&&m.body===p.body&&Math.abs(new Date(m.created_at).getTime()-new Date(p.created_at).getTime())<15000))];return merged.sort((a,b)=>a.created_at.localeCompare(b.created_at))})}},[]); const refreshReactions=useCallback(async(ids:string[],userId:string)=>{if(!ids.length)return;const {data}=await supabase.from('message_reactions').select('message_id,user_id,reaction').in('message_id',ids);const counts:Record<string,Record<string,number>>={};const mine:Record<string,string[]>={};(data||[]).forEach((r:any)=>{counts[r.message_id]??={};counts[r.message_id][r.reaction]=(counts[r.message_id][r.reaction]||0)+1;if(r.user_id===userId)(mine[r.message_id]??=[]).push(r.reaction)});setReactionCounts(counts);setMyReactions(mine)},[]);
  useEffect(()=>{let mounted=true; let channel:any; let refreshTimer:number|undefined; const removeExpired=()=>setMessages(prev=>{const now=Date.now(); const next=prev.filter(m=>new Date(m.expires_at).getTime()>now); return next.length===prev.length?prev:next}); const refreshNow=async()=>{await refresh(); removeExpired();}; const onVisibility=()=>{if(document.visibilityState==='visible')void refreshNow()}; const onOnline=()=>{setConnected(false); void supabase.realtime.connect(); void refreshNow()}; const onOffline=()=>setConnected(false); (async()=>{await refreshNow(); const {data:{session}}=await supabase.auth.getSession(); if(!session?.user||!mounted)return; sessionRef.current=session; const selfId=session.user.id; setAuthUserId(selfId); await supabase.realtime.setAuth(session.access_token); channel=supabase.channel('global-chat',{config:{presence:{key:selfId},private:true}}).on('presence',{event:'sync'},()=>{if(mounted)setOnline(Object.keys(channel.presenceState()).length)}).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages'},payload=>{if(!mounted)return;const m=payload.new as ChatMessage;if(new Date(m.expires_at).getTime()>Date.now()){setMessages(prev=>{if(prev.some(x=>x.id===m.id))return prev;if(m.user_id===selfId){const match=prev.find(x=>x.id.startsWith('optimistic-')&&x.user_id===selfId&&x.body===m.body&&Math.abs(new Date(x.created_at).getTime()-new Date(m.created_at).getTime())<15000);if(match){delete pendingRef.current[match.id];return prev.map(x=>x.id===match.id?m:x).sort((a,b)=>a.created_at.localeCompare(b.created_at))}return [...prev,m].sort((a,b)=>a.created_at.localeCompare(b.created_at))}return [...prev,m].sort((a,b)=>a.created_at.localeCompare(b.created_at))});if(m.user_id!==selfId)play('receive')}}).on('postgres_changes',{event:'DELETE',schema:'public',table:'messages'},payload=>setMessages(prev=>prev.filter(m=>m.id!==payload.old.id))).on('postgres_changes',{event:'*',schema:'public',table:'message_reactions'},()=>refreshReactions(messageIdsRef.current,selfId)).subscribe(async status=>{if(status==='SUBSCRIBED'){setConnected(true);await channel.track({online_at:new Date().toISOString()})}else if(status==='CHANNEL_ERROR'||status==='TIMED_OUT'){setConnected(false)}}); refreshTimer=window.setInterval(()=>void refreshNow(),10000); window.addEventListener('online',onOnline); window.addEventListener('offline',onOffline); document.addEventListener('visibilitychange',onVisibility);})(); return()=>{mounted=false;if(refreshTimer)window.clearInterval(refreshTimer);window.removeEventListener('online',onOnline);window.removeEventListener('offline',onOffline);document.removeEventListener('visibilitychange',onVisibility);if(channel){channel.untrack();supabase.removeChannel(channel)}};},[refresh]);
  useEffect(()=>{const timers: number[]=[]; const now=Date.now(); messages.forEach(m=>{const delay=new Date(m.expires_at).getTime()-now; if(delay>0&&delay<2147483647)timers.push(window.setTimeout(()=>setMessages(prev=>prev.filter(x=>x.id!==m.id)),delay+50));}); return()=>timers.forEach(t=>window.clearTimeout(t))},[messages]);
  useEffect(()=>{messagesRef.current=messages;messageIdsRef.current=messages.map(m=>m.id)},[messages]);
  const messageIds=useMemo(()=>messages.map(m=>m.id).join(','),[messages]);
  useEffect(()=>{if(authUserId&&messageIds)refreshReactions(messageIds.split(',').filter(Boolean),authUserId)},[messageIds,authUserId,refreshReactions]);
  const shouldStickToBottom=()=>{const el=listRef.current;if(!el)return true;return el.scrollHeight-el.scrollTop-el.clientHeight<120};
  useEffect(()=>{const el=listRef.current;if(el&&shouldStickToBottom())el.scrollTo({top:el.scrollHeight,behavior:'smooth'})},[messages.length]);
  const send=async()=>{if(sendLockRef.current)return;sendLockRef.current=true;setError('');const body=text.trim();const problem=validateMessage(text);if(problem){setError(problem);sendLockRef.current=false;return}const tempId=`optimistic-${crypto.randomUUID()}`;const createdAt=new Date().toISOString();const optimistic:ChatMessage={id:tempId,user_id:authUserId,name:profile.name,country:profile.country,subdivision:profile.subdivision,avatar_id:profile.avatarId,body,created_at:createdAt,expires_at:new Date(Date.now()+5*60*1000).toISOString()};pendingRef.current[tempId]={tempId,body,createdAt};setText('');setEmojiOpen(false);setMessages(prev=>prev.some(m=>m.id===tempId)?prev:[...prev,optimistic]);play('send');setSending(true);try{let session=sessionRef.current;if(!session){const {data}=await supabase.auth.getSession();session=data.session;sessionRef.current=session}const {data,error}=await supabase.functions.invoke('send-message',{body:{text:body,profile},headers:session?{Authorization:`Bearer ${session.access_token}`}:{}});if(error||data?.error)throw new Error(data?.error||'Unable to send message.');const serverMessage=(data?.message||data) as ChatMessage;setMessages(prev=>{if(serverMessage?.id&&prev.some(m=>m.id===serverMessage.id))return prev;const exists=prev.some(m=>m.id===tempId);return exists&&serverMessage?.id?prev.map(m=>m.id===tempId?serverMessage:m):prev});delete pendingRef.current[tempId]}catch(e:any){setMessages(prev=>prev.filter(m=>m.id!==tempId));delete pendingRef.current[tempId];setError(e.message||'Unable to send message. Please try again.')}finally{setSending(false);sendLockRef.current=false}};
  const onKey=(e:React.KeyboardEvent)=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};
  return <div className="chat-app"><header className="topbar"><div className="top-brand"><div className="brand-mini"><Earth3D small /></div><div><b>GLOBAL CHAT</b><span><i className={connected?'online-dot':'offline-dot'}></i>{online} Online</span></div></div><div className="top-actions"><button className="settings-btn" onClick={()=>setSettingsOpen(true)}><Settings size={18}/> SETTINGS</button></div></header>
    {!connected&&<div className="connection-banner">Reconnecting securely…</div>}
    <main className="chat-main"><div className="message-list" ref={listRef}>{messages.length===0?<div className="empty"><div className="empty-earth"><Earth3D /></div><h2>Talk to the world</h2><p>Say hello. Share ideas. Keep it friendly.</p></div>:messages.map(m=><Message key={m.id} m={m} current={m.user_id===authUserId} timeFormat={settings.timeFormat || '12h'} counts={reactionCounts[m.id]||{}} mine={myReactions[m.id]||[]} onToggle={async(r)=>{const {error}=await supabase.functions.invoke('toggle-reaction',{body:{messageId:m.id,reaction:r}});if(!error)refreshReactions(messageIdsRef.current,authUserId)}}/>)}</div>
      <div className="composer-wrap"><div className="composer"><div className="tools"><button className="icon-btn" onClick={()=>setEmojiOpen(v=>!v)} aria-label="Emoji"><Smile size={19}/></button>{emojiOpen&&<div className="emoji-pop">{EMOJIS.map(e=><button key={e} onClick={()=>setText(v=>v+e)}>{e}</button>)}</div>}</div><textarea value={text} maxLength={500} onChange={e=>setText(e.target.value)} onKeyDown={onKey} placeholder="Type your message..." rows={1}/><button className="send-btn" disabled={!text.trim()||sending} onClick={send}><Send size={18}/></button></div><div className="composer-meta"><span className={text.length>500?'danger':''}>{text.length} / 500</span>{error&&<span className="error-text">{error}</span>}<span className="input-note">English only · 3 messages / 10s</span></div></div>
    </main>{settingsOpen&&<SettingsPanel profile={profile} settings={settings} onClose={()=>setSettingsOpen(false)} onSave={async(p,s)=>{try{const {error}=await supabase.functions.invoke('save-profile',{body:p});if(error)throw error;onProfile(p);onSettings(s);localStorage.setItem(PROFILE_KEY,JSON.stringify(p));localStorage.setItem(SETTINGS_KEY,JSON.stringify(s));setSettingsOpen(false)}catch{setError('Could not save settings. Please try again.')}}}/>}</div>
}


function Earth3D({small=false}:{small?:boolean}){
  return <div className={`earth3d ${small?'earth3d-small':''}`} aria-hidden="true"><span className="earth3d-atmosphere"/><span className="earth3d-surface"><span className="earth3d-land earth3d-land-a"/><span className="earth3d-land earth3d-land-b"/><span className="earth3d-land earth3d-land-c"/><span className="earth3d-land earth3d-land-d"/></span><span className="earth3d-glow"/><span className="earth3d-shadow"/></div>
}

function formatMessageTime(value:string,format:TimeFormat){return new Intl.DateTimeFormat(undefined,{hour:format==='24h'?'2-digit':'numeric',minute:'2-digit',hour12:format==='12h'}).format(new Date(value))}

function Message({m,current,counts,mine,onToggle,timeFormat}:{m:ChatMessage;current:boolean;counts:Record<string,number>;mine:string[];onToggle:(r:string)=>Promise<void>;timeFormat:TimeFormat}){const avatar=<div className="avatar-bubble">{AVATARS.find(a=>a.id===m.avatar_id)?.emoji??'🌍'}</div>; const countryName=iso31661.find(c=>c.alpha2===m.country)?.name??m.country; const subdivisionName=iso31662.find(s=>s.code===m.subdivision)?.name??m.subdivision.split('-').pop()??m.subdivision; const head=<div className="message-head"><strong>{m.name}</strong><span>({subdivisionName}, {countryName})</span></div>; return <article className={`message-row ${current?'mine':''}`}><div className="message-content"><div className="message-top">{current?<>{head}{avatar}</>:<>{avatar}{head}</>}</div><div className="bubble-row">{current&&<time className="message-time" dateTime={m.created_at}>{formatMessageTime(m.created_at,timeFormat)}</time>}<div className="bubble">{m.body}</div>{!current&&<time className="message-time" dateTime={m.created_at}>{formatMessageTime(m.created_at,timeFormat)}</time>}</div><div className="reaction-row">{REACTIONS.map(r=><button key={r} className={mine.includes(r)?'reacted':''} onClick={()=>onToggle(r)}>{r}{counts[r]?<small>{counts[r]}</small>:null}</button>)}</div></div></article>}
function SettingsPanel({profile,settings,onClose,onSave}:{profile:Profile;settings:any;onClose:()=>void;onSave:(p:Profile,s:any)=>void}){const [p,setP]=useState(profile);const [s,setS]=useState(settings); const nameValid=p.name.trim().length>=2 && p.name.trim().length<=32; useEffect(()=>{const t=THEMES.find(x=>x.id===p.themeId)||THEMES[0]; document.documentElement.style.setProperty('--bg',t.bg);document.documentElement.style.setProperty('--surface',t.surface);document.documentElement.style.setProperty('--primary',t.primary);document.documentElement.style.setProperty('--accent',t.accent);document.documentElement.style.setProperty('--font-size',`${TEXT_SIZES[s.textSize as TextSize]}px`);},[p.themeId,s.textSize]); return <div className="modal-backdrop"><div className="settings-panel"><div className="panel-head"><div><b>⚙️ SETTINGS</b><span>Personalize your chat experience</span></div><button onClick={onClose}><X/></button></div><label>👤 Name / Nickname</label><input className="settings-name-input" maxLength={32} value={p.name} onChange={e=>setP({...p,name:e.target.value})} placeholder="Enter a nickname…" autoComplete="nickname"/><label>🖼️ Change Avatar</label><div className="avatar-grid compact">{AVATARS.map(a=><button className={`avatar ${p.avatarId===a.id?'selected':''}`} key={a.id} onClick={()=>setP({...p,avatarId:a.id})}>{a.emoji}</button>)}</div><label>🎨 Change Theme</label><div className="theme-grid compact-themes">{THEMES.map(t=><button className={`theme-tile ${p.themeId===t.id?'selected':''}`} key={t.id} style={{background:t.bg,borderColor:t.primary}} onClick={()=>setP({...p,themeId:t.id})}><span style={{background:t.primary}}></span><strong>{t.name}</strong></button>)}</div><label>🔤 Text Size</label><div className="segmented">{(['small','medium','large','xl'] as TextSize[]).map(k=><button className={s.textSize===k?'active':''} key={k} onClick={()=>setS({...s,textSize:k})}>{k==='xl'?'Extra Large':k[0].toUpperCase()+k.slice(1)}</button>)}</div><label>🔔 Sound</label><div className="segmented two"><button className={s.sound?'active':''} onClick={()=>setS({...s,sound:true})}><Volume2 size={15}/> ON</button><button className={!s.sound?'active':''} onClick={()=>setS({...s,sound:false})}><MicOff size={15}/> OFF</button></div><label>🕐 Clock Format</label><div className="segmented two"><button className={(s.timeFormat||'12h')==='12h'?'active':''} onClick={()=>setS({...s,timeFormat:'12h'})}>12-hour</button><button className={(s.timeFormat||'12h')==='24h'?'active':''} onClick={()=>setS({...s,timeFormat:'24h'})}>24-hour</button></div><button className="primary-btn" disabled={!nameValid} onClick={()=>onSave({...p,name:p.name.trim().replace(/\s+/g,' ')},{...s,timeFormat:s.timeFormat||'12h'})}>SAVE SETTINGS <Check size={17}/></button></div></div>}
