import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import { ArrowLeft, Mic, MicOff, Phone, PhoneCall, PhoneOff, Volume2, VolumeX, X } from 'lucide-react';
import { supabase } from './lib/supabase';
import { AVATARS } from './data/catalog';

type Friend = { user_id:string; name:string; avatar_id?:number };
type Call = { id:string; callerId:string; callerName:string; callerAvatar:number; recipientId:string; recipientName:string; recipientAvatar:number };
type Props = { userId:string; name:string; avatarId:number; friend:Friend|null; sound:boolean; blocked:boolean; onBack:()=>void; headerActions?:ReactNode };
const ICE:RTCConfiguration={iceServers:[{urls:'stun:stun.l.google.com:19302'}]};
const avatar=(id:number)=>AVATARS.find(x=>x.id===id)?.src||AVATARS[0].src;
const publishInbox=async(to:string,event:string,payload:any)=>{const ch=supabase.channel(`friend-call-inbox-${to}`);try{await new Promise<void>((resolve,reject)=>ch.subscribe((s:string)=>{if(s==='SUBSCRIBED')resolve();if(s==='CHANNEL_ERROR'||s==='TIMED_OUT')reject(new Error('Call signaling connection failed.'))}));await ch.send({type:'broadcast',event,payload})}finally{await supabase.removeChannel(ch)}};

export default function FriendsCallCenter({userId,name,avatarId,friend,sound,blocked,onBack,headerActions}:Props){
 const [incoming,setIncoming]=useState<Call|null>(null),[active,setActive]=useState<Call|null>(null),[status,setStatus]=useState<'calling'|'connecting'|'connected'>('calling'),[muted,setMuted]=useState(false),[speakerMuted,setSpeakerMuted]=useState(false),[remote,setRemote]=useState<MediaStream|null>(null),[error,setError]=useState('');
 const inbox=useRef<any>(null),room=useRef<any>(null),stream=useRef<MediaStream|null>(null),peer=useRef<RTCPeerConnection|null>(null),callRef=useRef<Call|null>(null),incomingRef=useRef<Call|null>(null),mounted=useRef(true);
 useEffect(()=>{incomingRef.current=incoming},[incoming]);
 const cleanup=useCallback(async()=>{try{peer.current?.close()}catch{}peer.current=null;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setRemote(null);if(room.current){await supabase.removeChannel(room.current);room.current=null}callRef.current=null;if(mounted.current){setActive(null);setIncoming(null);setMuted(false);setSpeakerMuted(false)}},[]);
 const mic=useCallback(async()=>{if(stream.current)return stream.current;if(!navigator.mediaDevices?.getUserMedia)throw new Error('Voice calls are not supported by this browser.');stream.current=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});return stream.current},[]);
 const send=(event:string,payload:any)=>{if(room.current)void room.current.send({type:'broadcast',event,payload})};
 const setupRoom=useCallback(async(call:Call)=>{
  const ch=supabase.channel(`friend-call-${call.id}`,{config:{presence:{key:userId},broadcast:{self:false,ack:true}}});room.current=ch;
  const ensure=async()=>{if(peer.current)return peer.current;const pc=new RTCPeerConnection(ICE);peer.current=pc;(await mic()).getTracks().forEach(t=>pc.addTrack(t,stream.current!));pc.ontrack=e=>{if(e.streams[0])setRemote(e.streams[0])};pc.onicecandidate=e=>{if(e.candidate)send('ice',{from:userId,to:userId===call.callerId?call.recipientId:call.callerId,candidate:e.candidate})};pc.onconnectionstatechange=()=>{if(pc.connectionState==='connected')setStatus('connected');if(pc.connectionState==='failed')setError('Call connection failed. Try again on a different network.')};return pc};
  ch.on('presence',{event:'sync'},()=>{const ids=Object.keys(ch.presenceState()).filter(x=>x!==userId);for(const id of ids)if(userId<id)void (async()=>{const pc=await ensure();if(pc.signalingState!=='stable')return;const offer=await pc.createOffer();await pc.setLocalDescription(offer);send('offer',{from:userId,to:id,description:offer})})().catch(e=>setError(e?.message||'Could not start call.'))});
  ch.on('presence',{event:'join'},({key}:any)=>{if(key&&key!==userId&&userId<key)void (async()=>{const pc=await ensure();if(pc.signalingState!=='stable')return;const offer=await pc.createOffer();await pc.setLocalDescription(offer);send('offer',{from:userId,to:key,description:offer})})().catch(e=>setError(e?.message||'Could not start call.'))});
  ch.on('broadcast' as any,{event:'offer'},async({payload}:any)=>{if(payload?.to!==userId||!payload?.description)return;try{const pc=await ensure();await pc.setRemoteDescription(payload.description);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);send('answer',{from:userId,to:payload.from,description:answer})}catch(e:any){setError(e?.message||'Could not answer call.')}});
  ch.on('broadcast' as any,{event:'answer'},async({payload}:any)=>{if(payload?.to!==userId||!payload?.description||!peer.current)return;try{await peer.current.setRemoteDescription(payload.description)}catch(e:any){setError(e?.message||'Could not connect call.')}});
  ch.on('broadcast' as any,{event:'ice'},async({payload}:any)=>{if(payload?.to!==userId||!payload?.candidate||!peer.current)return;try{await peer.current.addIceCandidate(payload.candidate)}catch{}});
  ch.on('broadcast' as any,{event:'end'},async({payload}:any)=>{if(payload?.from!==userId)await cleanup()});
  await new Promise<void>((resolve,reject)=>ch.subscribe((s:string)=>{if(s==='SUBSCRIBED')resolve();if(s==='CHANNEL_ERROR'||s==='TIMED_OUT')reject(new Error('Call signaling connection failed.'))}));
  await ch.track({userId,name,joinedAt:new Date().toISOString()});
 },[cleanup,mic,name,userId]);
 useEffect(()=>{mounted.current=true;const ch=supabase.channel(`friend-call-inbox-${userId}`,{config:{broadcast:{self:false,ack:true}}});inbox.current=ch;
  ch.on('broadcast' as any,{event:'invite'},({payload}:any)=>{if(!payload?.call||payload.call.recipientId!==userId)return;if(callRef.current||incomingRef.current){void publishInbox(payload.call.callerId,'busy',{callId:payload.call.id,from:userId});return}setError('');setIncoming(payload.call);if(sound){const a=new Audio('/sounds/receive.wav');a.volume=.45;void a.play().catch(()=>{})}});
  ch.on('broadcast' as any,{event:'accepted'},({payload}:any)=>{if(callRef.current?.id===payload?.callId)setStatus('connecting')});
  ch.on('broadcast' as any,{event:'declined'},({payload}:any)=>{if(callRef.current?.id===payload?.callId){setError('Your friend declined the call.');void cleanup()}});
  ch.on('broadcast' as any,{event:'busy'},({payload}:any)=>{if(callRef.current?.id===payload?.callId){setError('Your friend is already on another call.');void cleanup()}});
  ch.on('broadcast' as any,{event:'cancel'},({payload}:any)=>{if(incomingRef.current?.id===payload?.callId)setIncoming(null)});
  ch.subscribe();return()=>{mounted.current=false;void supabase.removeChannel(ch);inbox.current=null;void cleanup()};
 },[userId,sound,cleanup]);
 useEffect(()=>()=>{void cleanup()},[cleanup]);
 const start=async()=>{if(!friend||blocked||active)return;setError('');try{const {data,error:e}=await supabase.rpc('check_friend_call_target',{p_user_id:friend.user_id});if(e)throw e;if(!data)throw new Error('Voice calls are unavailable for this friend.');await mic();const call:Call={id:crypto.randomUUID(),callerId:userId,callerName:name,callerAvatar:avatarId,recipientId:friend.user_id,recipientName:friend.name,recipientAvatar:friend.avatar_id||1};callRef.current=call;setActive(call);setStatus('calling');await setupRoom(call);void publishInbox(call.recipientId,'invite',{call}).catch((e:any)=>{setError(e?.message||'Could not send call invitation.');void cleanup()})}catch(e:any){setError(e?.name==='NotAllowedError'?'Microphone permission was denied.':e?.message||'Could not start the call.');await cleanup()}};
 const accept=async()=>{const call=incoming;if(!call)return;setError('');try{const {data,error:e}=await supabase.rpc('check_friend_call_target',{p_user_id:call.callerId});if(e)throw e;if(!data)throw new Error('This call is unavailable.');await mic();callRef.current=call;setActive(call);setIncoming(null);setStatus('connecting');await setupRoom(call);void publishInbox(call.callerId,'accepted',{callId:call.id,from:userId})}catch(e:any){setError(e?.message||'Could not accept the call.');await cleanup()}};
 const decline=()=>{if(incoming)void publishInbox(incoming.callerId,'declined',{callId:incoming.id,from:userId});setIncoming(null)};
 const end=async()=>{send('end',{from:userId});if(active)void publishInbox(userId===active.callerId?active.recipientId:active.callerId,'cancel',{callId:active.id,from:userId});await cleanup()};
 const toggleMic=()=>{const next=!muted;stream.current?.getAudioTracks().forEach(t=>t.enabled=!next);setMuted(next)};
 return <>
  {friend&&<div className="friend-chat-call-actions"><button type="button" className="friend-back-icon-btn" onClick={onBack} title="Back to friends" aria-label="Back to friends"><ArrowLeft size={19}/></button><button type="button" className="friend-call-trigger" disabled={blocked||!!active} onClick={()=>void start()} title={blocked?'Unblock this friend to call':'Voice call'} aria-label="Start voice call"><PhoneCall size={17}/><span>Call</span></button>{headerActions}</div>}
  {error&&<div className="friend-call-toast" role="alert">{error}<button type="button" onClick={()=>setError('')} aria-label="Dismiss"><X size={14}/></button></div>}
  {incoming&&<div className="private-call-backdrop" role="alertdialog" aria-modal="true"><div className="private-incoming-call"><div className="private-incoming-icon"><PhoneCall size={28}/></div><span className="private-call-kicker">INCOMING VOICE CALL</span><img className="friend-call-avatar" src={avatar(incoming.callerAvatar)} alt=""/><h3>{incoming.callerName}</h3><p>Friends voice call</p><div className="private-incoming-actions"><button className="private-call-decline" onClick={decline}><PhoneOff size={17}/> DECLINE</button><button className="private-call-accept" onClick={()=>void accept()}><Phone size={17}/> ACCEPT</button></div></div></div>}
  {active&&<div className="private-active-call friend-active-call"><div className="private-active-call-head"><div><span>FRIENDS VOICE CALL</span><strong>{status==='connected'?'CONNECTED':status==='connecting'?'CONNECTING...':'CALLING...'}</strong></div></div><div className="private-active-participants"><div className="private-active-person"><img className="friend-call-avatar" src={avatar(userId===active.callerId?active.recipientAvatar:active.callerAvatar)} alt=""/><span>{userId===active.callerId?active.recipientName:active.callerName}</span>{remote&&<audio autoPlay playsInline muted={speakerMuted} ref={el=>{if(el&&el.srcObject!==remote)el.srcObject=remote}}/>}</div></div><div className="private-active-controls"><button onClick={toggleMic} className={muted?'active':''} title={muted?'Turn microphone on':'Mute microphone'}>{muted?<MicOff size={18}/>:<Mic size={18}/>}<span>{muted?'MIC OFF':'MIC ON'}</span></button><button onClick={()=>setSpeakerMuted(v=>!v)} className={speakerMuted?'active':''} title={speakerMuted?'Unmute call audio':'Mute call audio'}>{speakerMuted?<VolumeX size={18}/>:<Volume2 size={18}/>}<span>{speakerMuted?'SOUND OFF':'SOUND ON'}</span></button><button className="danger" onClick={()=>void end()}><PhoneOff size={18}/><span>END</span></button></div></div>}
 </>;
}
