import { useEffect, useState } from 'react';
import { Database, Trash2 } from 'lucide-react';
const HISTORY_PREFIX='global-chat-search-history-v1:';
export default function LocalDataCleanupControls({retentionDays,onRetentionDaysChange}:{retentionDays:number;onRetentionDaysChange:(days:number)=>void}){
 const [cleanupHistory,setCleanupHistory]=useState(true),[cleanupRoomCache,setCleanupRoomCache]=useState(false),[cleanupHiddenRecords,setCleanupHiddenRecords]=useState(false),[cleanupScroll,setCleanupScroll]=useState(false),[status,setStatus]=useState('');
 useEffect(()=>{const clean=()=>{if(retentionDays<=0)return;const cutoff=Date.now()-retentionDays*86400000;try{for(let i=localStorage.length-1;i>=0;i--){const key=localStorage.key(i);if(!key?.startsWith(HISTORY_PREFIX))continue;const rows=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(rows))localStorage.setItem(key,JSON.stringify(rows.filter((row:any)=>Number(row.at)>=cutoff)))}}catch{}};clean()},[retentionDays]);
 const cleanup=()=>{let removed=0;try{if(cleanupHistory){for(let i=localStorage.length-1;i>=0;i--){const key=localStorage.key(i);if(key?.startsWith(HISTORY_PREFIX)){localStorage.removeItem(key);removed++}}}if(cleanupRoomCache){for(const key of ['global-chat-your-private-chats-cache-v1','global-chat-your-private-chats-hidden-v1','global-chat-your-private-chats-pinned-v1'])if(localStorage.getItem(key)!==null){localStorage.removeItem(key);removed++}}if(cleanupHiddenRecords){for(const key of ['global-chat-local-deleted-v1','global-chat-voice-local-deleted-v1','global-chat-private-local-deleted-v1'])if(localStorage.getItem(key)!==null){localStorage.removeItem(key);removed++}}if(cleanupScroll){for(let i=localStorage.length-1;i>=0;i--){const key=localStorage.key(i);if(key?.startsWith('global-chat-scroll-position-v1:')){localStorage.removeItem(key);removed++}}}}catch{}setStatus(`${removed} local item${removed===1?'':'s'} cleared. Account settings and remote messages were not changed.`)};
 return <section className="settings-privacy-controls local-data-cleanup"><h3><Database size={17}/> Local data cleanup</h3><p>Choose how long to retain recent searches and which browser caches to clear. This does not delete messages from the service.</p><label>Search history retention<select value={retentionDays} onChange={event=>onRetentionDaysChange(Number(event.target.value))}><option value={30}>30 days</option><option value={90}>90 days</option><option value={365}>1 year</option><option value={0}>Keep until cleared</option></select></label><div className="local-cleanup-options"><label><input type="checkbox" checked={cleanupHistory} onChange={event=>setCleanupHistory(event.target.checked)}/> Search history</label><label><input type="checkbox" checked={cleanupRoomCache} onChange={event=>setCleanupRoomCache(event.target.checked)}/> Private chat list and pin cache</label><label><input type="checkbox" checked={cleanupHiddenRecords} onChange={event=>setCleanupHiddenRecords(event.target.checked)}/> Locally hidden message records</label><label><input type="checkbox" checked={cleanupScroll} onChange={event=>setCleanupScroll(event.target.checked)}/> Saved reading positions</label></div><button type="button" className="settings-password-save" onClick={cleanup}><Trash2 size={15}/> CLEAR SELECTED LOCAL DATA</button>{status&&<small className="settings-session-message" role="status">{status}</small>}</section>;
}
