import { useEffect, useState } from 'react';
import { Eye, ShieldCheck, X } from 'lucide-react';
import { supabase } from './lib/supabase';
export default function PrivacyReviewCard({userId,profile,settings,onProfileChange,onSettingChange}:{userId:string;profile:any;settings:any;onProfileChange:(update:(previous:any)=>any)=>void;onSettingChange:(key:string,value:any)=>void}){
 const [open,setOpen]=useState(false),[devices,setDevices]=useState<any[]>([]),[deviceError,setDeviceError]=useState('');
 useEffect(()=>{if(!open||!userId)return;let active=true;void supabase.from('account_device_history').select('device_key,device_type,first_seen_at,last_seen_at').eq('user_id',userId).order('last_seen_at',{ascending:false}).limit(12).then(({data,error})=>{if(!active)return;if(error)setDeviceError('Sign-in history is not available yet. Apply the latest database migration.');else setDevices(data||[])});return()=>{active=false}},[open,userId]);
 let nicknameCount=0;try{nicknameCount=Object.keys(JSON.parse(localStorage.getItem(`global-chat-friend-nicknames-v1:${userId}`)||'{}')).length}catch{}
 return <section className="settings-privacy-controls privacy-review-card"><h3><ShieldCheck size={17}/> Privacy review</h3><p>Review profile visibility, sign-in devices, local nicknames, and message previews in one place.</p><button type="button" className="settings-password-save" onClick={()=>setOpen(true)}>REVIEW PRIVACY CHOICES</button>{open&&<div className="feature-modal-backdrop privacy-review-backdrop" role="dialog" aria-modal="true" aria-labelledby="privacy-review-title"><section className="feature-modal privacy-review-modal"><header><div><b id="privacy-review-title"><ShieldCheck size={17}/> Privacy review</b><small>These changes are saved with Settings</small></div><button type="button" onClick={()=>setOpen(false)} aria-label="Close privacy review"><X size={18}/></button></header><div className="privacy-review-content"><section><h4>Profile visibility</h4><label><input type="checkbox" checked={profile.showCountry!==false} onChange={event=>onProfileChange(previous=>({...previous,showCountry:event.target.checked}))}/> Show my country</label><label><input type="checkbox" checked={profile.showSubdivision!==false} onChange={event=>onProfileChange(previous=>({...previous,showSubdivision:event.target.checked}))}/> Show my state or region</label><label>Profile intro visibility<select value={profile.profileIntroVisibility||'hidden'} onChange={event=>onProfileChange(previous=>({...previous,profileIntroVisibility:event.target.value}))}><option value="hidden">Hidden</option><option value="friends">Friends only</option><option value="everyone">Everyone</option></select></label></section><section><h4>Notification previews</h4><div className="segmented two"><button type="button" className={settings.notificationMessagePreview!==false?'active':''} onClick={()=>onSettingChange('notificationMessagePreview',true)}>Show text</button><button type="button" className={settings.notificationMessagePreview===false?'active':''} onClick={()=>onSettingChange('notificationMessagePreview',false)}>Hide text</button></div></section><section><h4>Local friend nicknames</h4><p>{nicknameCount} nickname{nicknameCount===1?'':'s'} stored only in this browser. Open Friends → a friend’s menu to edit or remove one.</p></section><section><h4>Recent sign-ins</h4>{deviceError?<p role="status">{deviceError}</p>:devices.length===0?<p>No sign-in history has been recorded yet.</p>:<ul>{devices.map(item=><li key={item.device_key}><strong>{item.device_type}</strong><small>Last used {new Date(item.last_seen_at).toLocaleString()}</small></li>)}</ul>}<p className="privacy-review-note">Device type and approximate sign-in times are stored. IP addresses and location are not collected.</p></section></div><footer><button type="button" className="primary-btn" onClick={()=>setOpen(false)}>DONE</button></footer></section></div>}</section>;
}
