import { useEffect, useState } from 'react';
import { BookOpen, Plus, Trash2, X } from 'lucide-react';
import { supabase } from './lib/supabase';

type Entry={id:string;room_id:string;user_id:string;term:string;definition:string;created_at:string};
export default function RoomGlossary({roomId,userId}:{roomId:string;userId:string}){
 const [open,setOpen]=useState(false),[entries,setEntries]=useState<Entry[]>([]),[term,setTerm]=useState(''),[definition,setDefinition]=useState(''),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!open)return;let active=true;setLoading(true);void supabase.from('private_room_glossary').select('*').eq('room_id',roomId).order('term').then(({data,error:loadError})=>{if(!active)return;if(loadError)setError('Could not load the room glossary.');else setEntries((data||[]) as Entry[]);setLoading(false)});return()=>{active=false}},[open,roomId]);
 const save=async()=>{if(!term.trim()||!definition.trim()||busy)return;setBusy(true);setError('');const {data,error:saveError}=await supabase.rpc('save_private_room_glossary_term',{p_room_id:roomId,p_term:term.trim(),p_definition:definition.trim()});if(saveError)setError(saveError.message);else if(data){setEntries(previous=>[...previous.filter(item=>item.term.toLowerCase()!==data.term.toLowerCase()),data as Entry].sort((a,b)=>a.term.localeCompare(b.term)));setTerm('');setDefinition('')}setBusy(false)};
 const remove=async(entry:Entry)=>{const {error:removeError}=await supabase.rpc('delete_private_room_glossary_term',{p_entry_id:entry.id});if(removeError)setError(removeError.message);else setEntries(previous=>previous.filter(item=>item.id!==entry.id))};
 return <><button type="button" onClick={()=>{setError('');setOpen(true)}}><BookOpen size={17}/><span>Room glossary</span></button>{open&&<div className="feature-modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="room-glossary-title"><section className="feature-modal room-glossary-modal"><header><div><b id="room-glossary-title">Room glossary</b><small>Shared with current room members</small></div><button type="button" onClick={()=>setOpen(false)} aria-label="Close glossary"><X size={18}/></button></header><div className="room-glossary-entries" aria-busy={loading}>{loading?<p>Loading glossary…</p>:entries.length===0?<p>No terms yet. Add a room-specific word or phrase.</p>:entries.map(entry=><article key={entry.id}><div><strong>{entry.term}</strong><p>{entry.definition}</p><small>Added by {entry.user_id===userId?'you':'a room member'}</small></div>{(entry.user_id===userId)&&<button type="button" onClick={()=>void remove(entry)} aria-label={`Remove ${entry.term}`}><Trash2 size={15}/></button>}</article>)}</div><div className="room-glossary-form"><label>Term<input maxLength={60} value={term} onChange={event=>setTerm(event.target.value)} placeholder="e.g. BRB"/></label><label>Definition<textarea maxLength={280} rows={2} value={definition} onChange={event=>setDefinition(event.target.value)} placeholder="What it means in this room"/></label><button type="button" disabled={busy||!term.trim()||!definition.trim()} onClick={()=>void save()}><Plus size={15}/>{busy?'Saving…':'Add or update term'}</button></div>{error&&<p className="room-glossary-error" role="alert">{error}</p>}</section></div>}</>;
}
