import { useEffect,useState } from 'react';
import { Clock3,Trash2,X } from 'lucide-react';
import { supabase } from './lib/supabase';
import type {ChatTextContext} from './lib/reconnectQueue';
type Scheduled={id:string;context:ChatTextContext;body:string;scheduled_at:string;status:'pending'|'sent'|'failed'|'cancelled';status_message:string|null};
export type ScheduleTarget={context:ChatTextContext;targetId:string|null;initialText?:string;onCreated?:()=>void};
export function ScheduleTextModal({target,profile,initialText,onClose,onCreated}:{target:ScheduleTarget;profile:{name:string;country:string;subdivision:string;avatarId:number};initialText:string;onClose:()=>void;onCreated:()=>void}){
 const toLocal=(d:Date)=>{const offset=d.getTimezoneOffset()*60000;return new Date(d.getTime()-offset).toISOString().slice(0,16)};
 const [body,setBody]=useState(initialText),[when,setWhen]=useState(()=>toLocal(new Date(Date.now()+10*60*1000))),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const save=async()=>{const date=new Date(when);if(!body.trim()||!Number.isFinite(date.getTime())){setError('Enter the message and a valid time.');return}setBusy(true);setError('');const {data,error}=await supabase.functions.invoke('schedule-text',{body:{context:target.context,targetId:target.targetId,body:body.trim(),scheduledAt:date.toISOString()}});if(error||data?.error)setError(data?.error||error?.message||'Could not schedule this message.');else{onCreated();onClose()}setBusy(false)};
 return <div className="feature-modal-backdrop schedule-text-backdrop" role="dialog" aria-modal="true" aria-labelledby="schedule-text-title" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="feature-modal schedule-text-modal"><header><div><b id="schedule-text-title"><Clock3 size={18}/> Schedule Text</b><small>Saved on the server and sent even if you are offline. Pick a time within 30 days.</small></div><button onClick={onClose} aria-label="Close"><X size={18}/></button></header><label>Message</label><textarea maxLength={550} value={body} onChange={e=>setBody(e.target.value)} placeholder="Write your message…"/><small className="composer-character-count" aria-live="polite">{[...body].length}/550 · {550-[...body].length} left</small><label>Send at</label><input type="datetime-local" min={toLocal(new Date(Date.now()+60*1000))} max={toLocal(new Date(Date.now()+30*24*60*60*1000))} value={when} onChange={e=>setWhen(e.target.value)}/>{error&&<p className="feature-modal-error" role="alert">{error}</p>}<div className="feature-modal-actions"><button type="button" className="secondary-btn" onClick={onClose}>Cancel</button><button type="button" className="primary-btn" disabled={busy||!body.trim()} onClick={()=>void save()}>{busy?'Saving…':'Schedule message'}</button></div></section></div>
}
export default function ScheduledMessagesPanel({onClose}:{onClose:()=>void}){
 const [rows,setRows]=useState<Scheduled[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const load=async()=>{const {data,error}=await supabase.from('scheduled_text_messages').select('id,context,body,scheduled_at,status,status_message').order('scheduled_at',{ascending:false}).limit(100);if(error)setError(error.message);else{setError('');setRows((data||[]) as Scheduled[])}setLoading(false)};
 useEffect(()=>{void load();const ch=supabase.channel('scheduled-text-updates').on('postgres_changes',{event:'*',schema:'public',table:'scheduled_text_messages'},()=>void load()).subscribe();const poll=window.setInterval(()=>void load(),30000);return()=>{window.clearInterval(poll);void supabase.removeChannel(ch)}},[]);
 const cancel=async(id:string)=>{const {error}=await supabase.from('scheduled_text_messages').delete().eq('id',id).eq('status','pending');if(error)setError(error.message);else setRows(v=>v.filter(x=>x.id!==id))};
 return <div className="feature-modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="scheduled-list-title" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="feature-modal scheduled-list-panel"><header><div><b id="scheduled-list-title"><Clock3 size={18}/> Scheduled Messages</b><small>Pending messages are sent automatically at their scheduled time. Status updates may take up to a minute.</small></div><button onClick={onClose} aria-label="Close"><X size={18}/></button></header>{error&&<p className="feature-modal-error" role="alert">{error}</p>}{loading?<p>Loading…</p>:rows.length?rows.map(row=><article className="scheduled-message-card" key={row.id}><div><b>{new Date(row.scheduled_at).toLocaleString()}</b><small>{row.context} chat · {row.status}{row.status_message?` · ${row.status_message}`:''}</small><p>{row.body}</p></div>{row.status==='pending'&&<button type="button" onClick={()=>void cancel(row.id)} aria-label="Cancel scheduled message" title="Cancel"><Trash2 size={16}/></button>}</article>):<p className="feature-empty">No scheduled messages.</p>}</section></div>
}
