create extension if not exists pgcrypto;
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types) values ('voice-messages','voice-messages',true,358400,array['audio/webm','audio/mp4','audio/x-m4a']) on conflict (id) do update set public=true,file_size_limit=358400,allowed_mime_types=array['audio/webm','audio/mp4','audio/x-m4a'];
create table if not exists public.voice_messages (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,country text not null,subdivision text not null,avatar_id integer not null check (avatar_id between 1 and 100),audio_url text not null,storage_path text not null unique,duration_ms integer not null check (duration_ms between 500 and 60000),file_size integer not null check (file_size between 1 and 358400),created_at timestamptz not null default now(),expires_at timestamptz not null default (now()+interval '3 minutes'));
alter table public.voice_messages enable row level security;
drop policy if exists voice_messages_select_active on public.voice_messages;
create policy voice_messages_select_active on public.voice_messages for select to authenticated using (expires_at>now());
grant select on public.voice_messages to authenticated;
grant select,insert,update,delete on public.voice_messages to service_role;
-- alter publication supabase_realtime add table public.voice_messages;
create or replace function public.accept_voice_message(p_user_id uuid,p_name text,p_country text,p_subdivision text,p_avatar_id integer,p_audio_url text,p_storage_path text,p_duration_ms integer,p_file_size integer) returns public.voice_messages language plpgsql security definer set search_path=public as $$ declare v public.voice_messages; recent_count integer; begin if auth.uid() is null or auth.uid()<>p_user_id then raise exception 'unauthorized'; end if; perform pg_advisory_xact_lock(hashtextextended(p_user_id::text,190914)); select count(*) into recent_count from public.voice_messages where user_id=p_user_id and created_at>now()-interval '10 seconds'; if recent_count>=3 then raise exception 'rate_limited'; end if; if char_length(trim(p_name)) not between 2 and 32 then raise exception 'invalid_name'; end if; if p_avatar_id not between 1 and 100 then raise exception 'invalid_avatar'; end if; if p_duration_ms<500 or p_duration_ms>60000 then raise exception 'duration_invalid'; end if; if p_file_size<1 or p_file_size>358400 then raise exception 'file_too_large'; end if; insert into public.voice_messages(user_id,name,country,subdivision,avatar_id,audio_url,storage_path,duration_ms,file_size) values(p_user_id,trim(p_name),p_country,p_subdivision,p_avatar_id,p_audio_url,p_storage_path,p_duration_ms,p_file_size) returning * into v; return v; end; $$;
revoke all on function public.accept_voice_message(uuid,text,text,text,integer,text,text,integer,integer) from public; grant execute on function public.accept_voice_message(uuid,text,text,text,integer,text,text,integer,integer) to authenticated;
create or replace function public.delete_voice_message_for_everyone(p_voice_id uuid) returns public.voice_messages language plpgsql security definer set search_path=public as $$ declare v public.voice_messages; begin delete from public.voice_messages where id=p_voice_id and user_id=auth.uid() and expires_at>now() returning * into v; if v.id is null then raise exception 'not_found'; end if; return v; end; $$;
revoke all on function public.delete_voice_message_for_everyone(uuid) from public; grant execute on function public.delete_voice_message_for_everyone(uuid) to authenticated;
create extension if not exists pg_net;
select cron.schedule('global-chat-voice-expiry','* * * * *',$$select net.http_post(url:='https://swrjhypfsbvlxlrpbsve.supabase.co/functions/v1/cleanup-voice-messages',headers:='{"Content-Type":"application/json"}'::jsonb,body:='{}'::jsonb);$$);

